require "tmpdir"
require "cybertrain/test"
require "cybertrain/generator"

# Gen::ViewsEmitter writes gen/views.rb: an empty table by default, the
# whole app/views tree with --embed-views. CRuby-portable (text only).

FIXTURE = "test/fixtures/embed_app"

test "literal escapes what a double-quoted Ruby string needs and nothing else" do
  assert_equal "\"plain\"", Cybertrain::Gen::ViewsEmitter.literal("plain")
  assert_equal "\"a\\\"b\"", Cybertrain::Gen::ViewsEmitter.literal("a\"b")
  assert_equal "\"a\\\\b\"", Cybertrain::Gen::ViewsEmitter.literal("a\\b")
  assert_equal "\"\\\#{x}\"", Cybertrain::Gen::ViewsEmitter.literal("\#{x}")
  assert_equal "\"l1\\nl2\\r\\tz\"", Cybertrain::Gen::ViewsEmitter.literal("l1\nl2\r\tz")
  assert_equal "\"こんにちは\"", Cybertrain::Gen::ViewsEmitter.literal("こんにちは")
end

test "view_files lists every file under app/views, sorted, relative" do
  assert_equal ["layouts/application.html.erb", "pages/hello.html.erb"],
               Cybertrain::Gen::ViewsEmitter.view_files("#{FIXTURE}/app/views")
  assert_equal 0, Cybertrain::Gen::ViewsEmitter.view_files("#{FIXTURE}/no_such_dir").size
end

test "without --embed-views the table is empty and the env is untouched" do
  source = Cybertrain::Gen::ViewsEmitter.emit(FIXTURE, false)
  assert_equal <<~RUBY, source
    # Generated by `spin run gen`. Do not edit.
    # Empty: this build reads app/views/ from disk. `spin run gen -- --embed-views`
    # (what `cybertrain build` runs) fills it and the binary stops reading disk.
    module Gen
      module Views
        SOURCES = { "" => "" }
        SOURCES.delete("")
      end
    end
  RUBY
  assert_nil source.index("CYBERTRAIN_ENV")
end

test "with --embed-views every view is a literal and production becomes the default env" do
  source = Cybertrain::Gen::ViewsEmitter.emit(FIXTURE, true)
  assert_equal File.read("#{FIXTURE}/gen/views.rb"), source
  assert_includes source, "\"pages/hello.html.erb\" => \"<%\\# locals: (name:) %>\\n<h1>こんにちは \\\"<%= name %>\\\"</h1>\\n<p>backslash \\\\ and \\\#{not interpolated} and\\ttab</p>\\n\","
  assert_includes source, "ENV[\"CYBERTRAIN_ENV\"] = \"production\" if (ENV[\"CYBERTRAIN_ENV\"] || \"\").empty?\n"
end

test "with --embed-views and no app/views, the table is still typed empty, not a bare {}" do
  source = Cybertrain::Gen::ViewsEmitter.emit("#{FIXTURE}/no_such_dir", true)
  assert_includes source, "SOURCES = { \"\" => \"\" }\n"
  assert_includes source, "SOURCES.delete(\"\")\n"
  assert_includes source, "ENV[\"CYBERTRAIN_ENV\"] = \"production\" if (ENV[\"CYBERTRAIN_ENV\"] || \"\").empty?\n"
end

# A throwaway app tree for the runner integration test below. Built at
# top level (not inside a `test` block: Dir.mktmpdir's return type is
# polymorphic on whether a block is given, and Spinel does not widen that
# across a call made from inside a stored block, spikes/NOTES.md rule 30)
# so it matches the pattern gen_manifest.rb and gen_runner_models.rb use.
RUNNER_ROOT = Dir.mktmpdir("cybertrain-gen-views")
Dir.mkdir("#{RUNNER_ROOT}/app")
Dir.mkdir("#{RUNNER_ROOT}/app/views")
File.write("#{RUNNER_ROOT}/app/views/a.html.erb", "<p>a</p>\n")
Dir.mkdir("#{RUNNER_ROOT}/app/controllers")

at_exit do
  ["gen/views.rb", "gen/routes.rb", "gen/controllers.rb", "gen/app.rb", "app/views/a.html.erb"].each do |f|
    File.delete("#{RUNNER_ROOT}/#{f}") if File.exist?("#{RUNNER_ROOT}/#{f}")
  end
  ["gen", "app/views", "app/controllers", "app"].each do |d|
    Dir.rmdir("#{RUNNER_ROOT}/#{d}") if File.directory?("#{RUNNER_ROOT}/#{d}")
  end
  Dir.rmdir(RUNNER_ROOT)
end

test "the runner writes gen/views.rb, empty by default and full with --embed-views" do
  Cybertrain::Routes.reset!
  Cybertrain::Gen::Runner.run(RUNNER_ROOT, [])
  assert_nil File.read("#{RUNNER_ROOT}/gen/views.rb").index("a.html.erb")
  Cybertrain::Gen::Runner.run(RUNNER_ROOT, ["--embed-views"])
  assert_includes File.read("#{RUNNER_ROOT}/gen/views.rb"), "\"a.html.erb\" => \"<p>a</p>\\n\","
  Cybertrain::Gen::Runner.run(RUNNER_ROOT, [])
  assert_nil File.read("#{RUNNER_ROOT}/gen/views.rb").index("a.html.erb")
end

Cybertrain::Test.run!
