require "cybertrain/test"
require "cybertrain/schema"
require "cybertrain/generator/model_scan"
require "cybertrain/generator/models_emitter"

# Pure text tests of the model generator (no database: CRuby-portable).
# The expected sources below are copied verbatim from test/model.rb, the
# hand-written executable specification of the generated shape.

def model_spec_schema
  Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "posts" do |t|
      t.string "title", null: false
      t.text "body"
      t.timestamps
    end
    s.create_table "comments" do |t|
      t.references :post
      t.string "author"
      t.text "body", null: false
      t.timestamps
    end
    s.create_table "flags" do |t|
      t.boolean "active", null: false, default: "false"
      t.float "score"
      t.string "group"
    end
  end
end

def emit_for(name, view_methods = [])
  definition = model_spec_schema
  Cybertrain::Gen::ModelsEmitter.emit(definition.table(name), definition, view_methods)
end

# One line of `source` per entry, compared after stripping indentation.
def assert_lines(source, lines)
  stripped = source.lines.map { |l| l.strip }
  lines.each do |line|
    Cybertrain::Test.count_assertion
    flunk("missing line: #{line}") unless stripped.include?(line)
  end
end

def refute_line(source, line)
  Cybertrain::Test.count_assertion
  stripped = source.lines.map { |l| l.strip }
  flunk("unexpected line: #{line}") if stripped.include?(line)
end

HEADER = "# Generated by `spin run gen` from db/schema.rb. Do not edit.\n"

EXPECTED_POST = HEADER + <<~'RUBY'
    class PostRelation < Cybertrain::Relation
      def where(h) = (add_where(h); self)
      def where_sql(s, b = []) = (add_where_sql(s, b); self)
      def order(o) = (set_order(o); self)
      def order_sql(s) = (add_order_sql(s); self)
      def limit(n) = (set_limit(n); self)
      def offset(n) = (set_offset(n); self)

      def to_a
        out = Array.new(0) { Post.new }
        rows.each { |r| out << Post.from_row(r) }
        out
      end

      def each(&blk) = to_a.each(&blk)

      def first
        r = first_row
        return nil if r.nil?
        Post.from_row(r)
      end

      def last
        r = last_row
        return nil if r.nil?
        Post.from_row(r)
      end

      def find_by(h) = where(h).first

      def find(id)
        rec = where(id: id).first
        raise Cybertrain::RecordNotFound, "Couldn't find Post with id=#{id}" if rec.nil?
        rec
      end

      def size = count
    end

    class Post < Cybertrain::Model
      def self.table_name = "posts"
      def self.column_names = ["id", "title", "body", "created_at", "updated_at"]
      def model_name = "Post"

      attr_accessor :title, :body, :created_at, :updated_at

      def initialize(attrs = {})
        super()
        @title = ""
        @body = nil
        @created_at = nil
        @updated_at = nil
        assign_attributes(attrs)
      end

      def self.from_row(row)
        rec = Post.new
        rec.load_row(row)
        rec
      end

      def load_row(row)
        set_id(Cybertrain::Cast.int(row["id"]))
        @title = Cybertrain::Cast.str(row["title"])
        @body = Cybertrain::Cast.str_or_nil(row["body"])
        @created_at = Cybertrain::Cast.time_or_nil(row["created_at"])
        @updated_at = Cybertrain::Cast.time_or_nil(row["updated_at"])
        mark_persisted!
        nil
      end

      def read_attribute(name)
        case name
        when :id then @id
        when :title then @title
        when :body then @body
        when :created_at then @created_at
        when :updated_at then @updated_at
        else nil
        end
      end

      def write_attribute(name, value)
        case name
        when :title then @title = Cybertrain::Cast.str(value)
        when :body then @body = Cybertrain::Cast.str_or_nil(value)
        when :created_at then @created_at = Cybertrain::Cast.time_or_nil(value)
        when :updated_at then @updated_at = Cybertrain::Cast.time_or_nil(value)
        end
        nil
      end

      def assign_attributes(attrs)
        attrs.each { |k, v| write_attribute(k.to_s.to_sym, v) }
        self
      end

      def to_row
        {
          "title" => Cybertrain::Cast.to_sql(@title),
          "body" => Cybertrain::Cast.to_sql(@body),
          "created_at" => Cybertrain::Cast.to_sql(@created_at),
          "updated_at" => Cybertrain::Cast.to_sql(@updated_at)
        }
      end

      def self.all = PostRelation.new("posts")
      def self.where(h) = all.where(h)
      def self.order(o) = all.order(o)
      def self.order_sql(s) = all.order_sql(s)
      def self.limit(n) = all.limit(n)
      def self.find(id) = all.find(id)
      def self.find_by(h) = all.find_by(h)
      def self.first = all.first
      def self.last = all.last
      def self.count = all.count

      def self.create(attrs = {})
        rec = Post.new(attrs)
        rec.save
        rec
      end

      def comments = CommentRelation.new("comments").where(post_id: @id).to_a

      def read_association(name)
        case name
        when :comments then self.comments
        else nil
        end
      end

      def call_view_method(name)
        case name
        when :summary then self.summary
        else nil
        end
      end
    end
  RUBY

EXPECTED_COMMENT = HEADER + <<~'RUBY'
    class CommentRelation < Cybertrain::Relation
      def where(h) = (add_where(h); self)
      def where_sql(s, b = []) = (add_where_sql(s, b); self)
      def order(o) = (set_order(o); self)
      def order_sql(s) = (add_order_sql(s); self)
      def limit(n) = (set_limit(n); self)
      def offset(n) = (set_offset(n); self)

      def to_a
        out = Array.new(0) { Comment.new }
        rows.each { |r| out << Comment.from_row(r) }
        out
      end

      def each(&blk) = to_a.each(&blk)

      def first
        r = first_row
        return nil if r.nil?
        Comment.from_row(r)
      end

      def last
        r = last_row
        return nil if r.nil?
        Comment.from_row(r)
      end

      def find_by(h) = where(h).first

      def find(id)
        rec = where(id: id).first
        raise Cybertrain::RecordNotFound, "Couldn't find Comment with id=#{id}" if rec.nil?
        rec
      end

      def size = count
    end

    class Comment < Cybertrain::Model
      def self.table_name = "comments"
      def self.column_names = ["id", "post_id", "author", "body", "created_at", "updated_at"]
      def model_name = "Comment"

      attr_accessor :post_id, :author, :body, :created_at, :updated_at

      def initialize(attrs = {})
        super()
        @post_id = 0
        @author = nil
        @body = ""
        @created_at = nil
        @updated_at = nil
        assign_attributes(attrs)
      end

      def self.from_row(row)
        rec = Comment.new
        rec.load_row(row)
        rec
      end

      def load_row(row)
        set_id(Cybertrain::Cast.int(row["id"]))
        @post_id = Cybertrain::Cast.int(row["post_id"])
        @author = Cybertrain::Cast.str_or_nil(row["author"])
        @body = Cybertrain::Cast.str(row["body"])
        @created_at = Cybertrain::Cast.time_or_nil(row["created_at"])
        @updated_at = Cybertrain::Cast.time_or_nil(row["updated_at"])
        mark_persisted!
        nil
      end

      def read_attribute(name)
        case name
        when :id then @id
        when :post_id then @post_id
        when :author then @author
        when :body then @body
        when :created_at then @created_at
        when :updated_at then @updated_at
        else nil
        end
      end

      def write_attribute(name, value)
        case name
        when :post_id then @post_id = Cybertrain::Cast.int(value)
        when :author then @author = Cybertrain::Cast.str_or_nil(value)
        when :body then @body = Cybertrain::Cast.str(value)
        when :created_at then @created_at = Cybertrain::Cast.time_or_nil(value)
        when :updated_at then @updated_at = Cybertrain::Cast.time_or_nil(value)
        end
        nil
      end

      def assign_attributes(attrs)
        attrs.each { |k, v| write_attribute(k.to_s.to_sym, v) }
        self
      end

      def to_row
        {
          "post_id" => Cybertrain::Cast.to_sql(@post_id),
          "author" => Cybertrain::Cast.to_sql(@author),
          "body" => Cybertrain::Cast.to_sql(@body),
          "created_at" => Cybertrain::Cast.to_sql(@created_at),
          "updated_at" => Cybertrain::Cast.to_sql(@updated_at)
        }
      end

      def self.all = CommentRelation.new("comments")
      def self.where(h) = all.where(h)
      def self.order(o) = all.order(o)
      def self.order_sql(s) = all.order_sql(s)
      def self.limit(n) = all.limit(n)
      def self.find(id) = all.find(id)
      def self.find_by(h) = all.find_by(h)
      def self.first = all.first
      def self.last = all.last
      def self.count = all.count

      def self.create(attrs = {})
        rec = Comment.new(attrs)
        rec.save
        rec
      end

      def post = Post.find_by(id: @post_id)

      def read_association(name)
        case name
        when :post then self.post
        else nil
        end
      end

      def call_view_method(name) = nil
    end
  RUBY

EXPECTED_FLAG = HEADER + <<~'RUBY'
    class FlagRelation < Cybertrain::Relation
      def where(h) = (add_where(h); self)
      def where_sql(s, b = []) = (add_where_sql(s, b); self)
      def order(o) = (set_order(o); self)
      def order_sql(s) = (add_order_sql(s); self)
      def limit(n) = (set_limit(n); self)
      def offset(n) = (set_offset(n); self)

      def to_a
        out = Array.new(0) { Flag.new }
        rows.each { |r| out << Flag.from_row(r) }
        out
      end

      def each(&blk) = to_a.each(&blk)

      def first
        r = first_row
        return nil if r.nil?
        Flag.from_row(r)
      end

      def last
        r = last_row
        return nil if r.nil?
        Flag.from_row(r)
      end

      def find_by(h) = where(h).first

      def find(id)
        rec = where(id: id).first
        raise Cybertrain::RecordNotFound, "Couldn't find Flag with id=#{id}" if rec.nil?
        rec
      end

      def size = count
    end

    class Flag < Cybertrain::Model
      def self.table_name = "flags"
      def self.column_names = ["id", "active", "score", "group"]
      def model_name = "Flag"

      attr_accessor :active, :score, :group

      def initialize(attrs = {})
        super()
        @active = false
        @score = nil
        @group = nil
        assign_attributes(attrs)
      end

      def self.from_row(row)
        rec = Flag.new
        rec.load_row(row)
        rec
      end

      def load_row(row)
        set_id(Cybertrain::Cast.int(row["id"]))
        @active = Cybertrain::Cast.bool(row["active"])
        @score = Cybertrain::Cast.float_or_nil(row["score"])
        @group = Cybertrain::Cast.str_or_nil(row["group"])
        mark_persisted!
        nil
      end

      def read_attribute(name)
        case name
        when :id then @id
        when :active then @active
        when :score then @score
        when :group then @group
        else nil
        end
      end

      def write_attribute(name, value)
        case name
        when :active then @active = Cybertrain::Cast.bool(value)
        when :score then @score = Cybertrain::Cast.float_or_nil(value)
        when :group then @group = Cybertrain::Cast.str_or_nil(value)
        end
        nil
      end

      def assign_attributes(attrs)
        attrs.each { |k, v| write_attribute(k.to_s.to_sym, v) }
        self
      end

      def to_row
        {
          "active" => Cybertrain::Cast.to_sql(@active),
          "score" => Cybertrain::Cast.to_sql(@score),
          "group" => Cybertrain::Cast.to_sql(@group)
        }
      end

      def self.all = FlagRelation.new("flags")
      def self.where(h) = all.where(h)
      def self.order(o) = all.order(o)
      def self.order_sql(s) = all.order_sql(s)
      def self.limit(n) = all.limit(n)
      def self.find(id) = all.find(id)
      def self.find_by(h) = all.find_by(h)
      def self.first = all.first
      def self.last = all.last
      def self.count = all.count

      def self.create(attrs = {})
        rec = Flag.new(attrs)
        rec.save
        rec
      end

      def read_association(name) = nil
      def call_view_method(name) = nil
    end
  RUBY

# ---- naming -------------------------------------------------------------

test "model_class_name singularizes and camelizes the table name" do
  assert_equal "Post", Cybertrain::Gen::ModelsEmitter.model_class_name("posts")
  assert_equal "Comment", Cybertrain::Gen::ModelsEmitter.model_class_name("comments")
  assert_equal "Person", Cybertrain::Gen::ModelsEmitter.model_class_name("people")
  assert_equal "Category", Cybertrain::Gen::ModelsEmitter.model_class_name("categories")
  assert_equal "BlogPost", Cybertrain::Gen::ModelsEmitter.model_class_name("blog_posts")
end

test "file_name is the singular table name" do
  assert_equal "post.rb", Cybertrain::Gen::ModelsEmitter.file_name("posts")
  assert_equal "blog_post.rb", Cybertrain::Gen::ModelsEmitter.file_name("blog_posts")
  assert_equal "person.rb", Cybertrain::Gen::ModelsEmitter.file_name("people")
end

# ---- the exact shape of test/model.rb -------------------------------------

test "posts emits exactly the Post shape of test/model.rb" do
  assert_equal EXPECTED_POST, emit_for("posts", ["summary"])
end

test "comments emits exactly the Comment shape of test/model.rb" do
  assert_equal EXPECTED_COMMENT, emit_for("comments")
end

test "flags emits exactly the Flag shape of test/model.rb" do
  assert_equal EXPECTED_FLAG, emit_for("flags")
end

# ---- the lines named by the plan ----------------------------------------

test "model_name and column_names lines" do
  post = emit_for("posts", ["summary"])
  assert_lines(post, [
    'def self.table_name = "posts"',
    'def self.column_names = ["id", "title", "body", "created_at", "updated_at"]',
    'def model_name = "Post"'
  ])
  comment = emit_for("comments")
  assert_lines(comment, [
    'def self.column_names = ["id", "post_id", "author", "body", "created_at", "updated_at"]',
    'def model_name = "Comment"',
    'class CommentRelation < Cybertrain::Relation',
    'class Comment < Cybertrain::Model'
  ])
end

test "casts per column follow type and null" do
  comment = emit_for("comments")
  assert_lines(comment, [
    '@post_id = Cybertrain::Cast.int(row["post_id"])',
    '@author = Cybertrain::Cast.str_or_nil(row["author"])',
    '@body = Cybertrain::Cast.str(row["body"])',
    '@created_at = Cybertrain::Cast.time_or_nil(row["created_at"])',
    'when :post_id then @post_id = Cybertrain::Cast.int(value)',
    'when :author then @author = Cybertrain::Cast.str_or_nil(value)',
    '@post_id = 0',
    '@author = nil',
    '@body = ""'
  ])
end

test "def post (belongs_to) and def comments (has_many)" do
  assert_lines(emit_for("comments"), ["def post = Post.find_by(id: @post_id)"])
  assert_lines(emit_for("posts"), ['def comments = CommentRelation.new("comments").where(post_id: @id).to_a'])
  refute_line(emit_for("flags"), "def post = Post.find_by(id: @post_id)")
end

test "read_association case covers belongs_to and has_many" do
  assert_lines(emit_for("posts"), ["def read_association(name)", "when :comments then self.comments"])
  assert_lines(emit_for("comments"), ["def read_association(name)", "when :post then self.post"])
  assert_lines(emit_for("flags"), ["def read_association(name) = nil"])
end

test "call_view_method with a scanned summary" do
  info = Cybertrain::Gen::ModelScan.scan_source("app/models/post.rb", "class Post\n  def summary = title[0, 3]\nend\n")
  post = emit_for("posts", info.view_methods)
  assert_lines(post, ["def call_view_method(name)", "when :summary then self.summary"])
  assert_lines(emit_for("comments"), ["def call_view_method(name) = nil"])
end

# ---- the column type map --------------------------------------------------

def typed_schema
  Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "events" do |t|
      t.string "name", null: false, default: "'untitled'"
      t.integer "seats", null: false, default: "10"
      t.integer "rank"
      t.integer "level", default: "3"
      t.float "price", null: false
      t.float "ratio", default: "0.5"
      t.boolean "public", null: false
      t.boolean "draft", default: "true"
      t.date "starts_on"
      t.datetime "published_at"
      t.text "notes", default: "NULL"
    end
  end
end

def events_source
  definition = typed_schema
  Cybertrain::Gen::ModelsEmitter.emit(definition.table("events"), definition, [])
end

test "integer, float, boolean, date and datetime casts" do
  assert_lines(events_source, [
    '@seats = Cybertrain::Cast.int(row["seats"])',
    '@rank = Cybertrain::Cast.int_or_nil(row["rank"])',
    '@price = Cybertrain::Cast.float(row["price"])',
    '@ratio = Cybertrain::Cast.float_or_nil(row["ratio"])',
    '@public = Cybertrain::Cast.bool(row["public"])',
    '@draft = Cybertrain::Cast.bool_or_nil(row["draft"])',
    '@starts_on = Cybertrain::Cast.str_or_nil(row["starts_on"])',
    '@published_at = Cybertrain::Cast.time_or_nil(row["published_at"])',
    'when :starts_on then @starts_on = Cybertrain::Cast.str_or_nil(value)',
    'when :published_at then @published_at = Cybertrain::Cast.time_or_nil(value)'
  ])
end

test "attributes stay attr_accessors (no def writers: NOTES rule 43) and order_sql is emitted" do
  post = emit_for("posts")
  assert_lines(post, ["attr_accessor :title, :body, :created_at, :updated_at", "def order_sql(s) = (add_order_sql(s); self)",
                      "def self.order_sql(s) = all.order_sql(s)"])
  refute_line(post, "attr_reader :title, :body, :created_at, :updated_at")
  refute post.include?("  def body=(v)\n"), "a def writer on a model breaks Response#body= under Spinel"
end

def raising_columns(name)
  Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "things" do |t|
      t.string name
    end
  end
end

def emit_error(name)
  definition = raising_columns(name)
  begin
    Cybertrain::Gen::ModelsEmitter.emit(definition.table("things"), definition, [])
    ""
  rescue ArgumentError => e
    e.message
  end
end

test "emit rejects column names that are invalid or collide with model methods" do
  ["errors", "persisted", "class", "hash", "inspect", "to_s",
   "attributes", "save", "update", "destroy", "reload", "model_name",
   "to_json", "as_json", "end", "def", "nil", "self", "BEGIN", "__FILE__",
   # The hooks Ruby calls on its own.
   "to_ary", "to_str", "to_hash", "to_proc", "to_int", "method_missing",
   # The one Kernel method the model calls on implicit self: a `raise` column
   # would turn Model#save!'s `raise RecordInvalid, ...` into a call of the reader.
   "raise", "fail"].each do |bad|
    assert emit_error(bad).include?("is reserved"), "#{bad} should be rejected"
  end
  ["1st", "a-b", "a b", "a.b", "", "valid?", "ünïcode"].each do |bad|
    assert emit_error(bad).include?("not a valid attribute name"), "#{bad.inspect} should be rejected"
  end
  # Names that only look like Model methods (the real ones end in `?`), and
  # the camelCase / capitalised columns of an existing schema: anything Ruby
  # takes as a method name generates (the scaffold alone insists on
  # snake_case for the names it invents).
  # ... and private Kernel methods nothing in the class calls are ordinary
  # columns (issues.open, documents.format, trucks.load).
  ["title", "_x", "a1", "group", "new_record", "is_a", "frozen", "createdAt", "userId", "Title", "X1",
   "open", "format", "load", "print", "select", "test", "sleep"].each do |ok|
    assert_equal "", emit_error(ok)
  end
  # Object methods nothing in Cybertrain calls on a record: accepted, with a
  # note in the generated file (an existing schema keeps generating).
  ["display", "tap", "methods", "send", "object_id", "freeze", "method", "instance_variable_get"].each do |noted|
    assert_equal "", emit_error(noted)
  end
  display = Cybertrain::Gen::ModelsEmitter.emit(raising_columns("display").table("things"), raising_columns("display"), [])
  assert_lines(display, [
    '# NOTE: column "display" shadows Object#display on this model (nothing in Cybertrain calls it on a record; Ident::SHADOWING_COLUMN_NAMES)',
    "attr_accessor :display"
  ])
end

test "an association reader named like an Object method keeps its name and gets the note a column gets" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "posts" do |t|
      t.string "title", null: false
      t.references :send, foreign_key: false
    end
    s.create_table "users" do |t|
      t.string "name", null: false
    end
    s.add_foreign_key "posts", "users", column: "send_id"
    s.create_table "methods" do |t|
      t.references :post
      t.string "body"
    end
  end
  post = Cybertrain::Gen::ModelsEmitter.emit(definition.table("posts"), definition, [])
  assert_lines(post, [
    '# NOTE: belongs_to reader "send" shadows Object#send on this model (nothing in Cybertrain calls it on a record; Ident::SHADOWING_COLUMN_NAMES)',
    "def send = User.find_by(id: @send_id)",
    '# NOTE: has_many reader "methods" shadows Object#methods on this model (nothing in Cybertrain calls it on a record; Ident::SHADOWING_COLUMN_NAMES)',
    'def methods = MethodRelation.new("methods").where(post_id: @id).to_a'
  ])
end

test "a capitalised foreign key gets a capitalised reader, dispatched with an explicit receiver" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "users" do |t|
      t.string "name", null: false
    end
    s.create_table "posts" do |t|
      t.integer "Author_id", null: false
    end
    s.add_foreign_key "posts", "users", column: "Author_id"
  end
  post = Cybertrain::Gen::ModelsEmitter.emit(definition.table("posts"), definition, [])
  # Bare, `Author` would be a constant lookup; `self.Author` is the reader.
  assert_lines(post, ["def Author = User.find_by(id: @Author_id)", "when :Author then self.Author"])
end

test "an association named like a Model method moves to its fallback name instead of shadowing it" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "posts" do |t|
      t.string "title", null: false
    end
    s.create_table "errors" do |t|
      t.references :post
      t.string "message"
    end
    s.create_table "things" do |t|
      t.references :hash, foreign_key: false
    end
    s.create_table "hashes" do |t|
      t.string "digest"
    end
    s.add_foreign_key "things", "hashes", column: "hash_id"
  end
  # Post#errors stays Model#errors; the derived has_many takes <table>_as_<stem>.
  post = Cybertrain::Gen::ModelsEmitter.emit(definition.table("posts"), definition, [])
  assert_lines(post, [
    '# has_many errors reads as errors_as_post: "errors" is a column, another association or a Cybertrain::Model method',
    'def errors_as_post = ErrorRelation.new("errors").where(post_id: @id).to_a',
    "when :errors_as_post then self.errors_as_post"
  ])
  refute post.include?("def errors ")
  # Thing#hash stays Object#hash; the belongs_to takes <stem>_as_<column>.
  thing = Cybertrain::Gen::ModelsEmitter.emit(definition.table("things"), definition, [])
  assert_lines(thing, [
    '# belongs_to hash_id reads as hash_as_hash_id: "hash" is a column, another association or a Cybertrain::Model method',
    "def hash_as_hash_id = Hash.find_by(id: @hash_id)",
    "when :hash_as_hash_id then self.hash_as_hash_id"
  ])
  refute thing.include?("def hash ")
end

test "a column named like an association reader keeps its name; the association moves to its fallback name" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "articles" do |t|
      t.string "title", null: false
      t.text "comments"
    end
    s.create_table "comments" do |t|
      t.references :article
      t.string "article"
    end
    # The fallback name itself taken by a column: now there is nothing left.
    s.create_table "notes" do |t|
      t.text "tags"
      t.text "tags_as_note"
    end
    s.create_table "tags" do |t|
      t.references :note
    end
  end
  # articles.comments (a text column) wins the plain name, as it did before
  # the generator checked for the clash; the association is not lost.
  article = Cybertrain::Gen::ModelsEmitter.emit(definition.table("articles"), definition, [])
  assert_lines(article, [
    "attr_accessor :title, :comments",
    '# has_many comments reads as comments_as_article: "comments" is a column, another association or a Cybertrain::Model method',
    'def comments_as_article = CommentRelation.new("comments").where(article_id: @id).to_a',
    "when :comments_as_article then self.comments_as_article"
  ])
  refute article.include?("def comments ")
  # comments.article (a string column) next to comments.article_id: the
  # column keeps `article`, the belongs_to reads as article_as_article_id --
  # a schema that generated before PR #10 still generates.
  comment = Cybertrain::Gen::ModelsEmitter.emit(definition.table("comments"), definition, [])
  assert_lines(comment, [
    "attr_accessor :article_id, :article",
    '# belongs_to article_id reads as article_as_article_id: "article" is a column, another association or a Cybertrain::Model method',
    "def article_as_article_id = Article.find_by(id: @article_id)",
    "when :article_as_article_id then self.article_as_article_id"
  ])
  refute comment.include?("def article ")
  note = assert_raises("ArgumentError") do
    Cybertrain::Gen::ModelsEmitter.emit(definition.table("notes"), definition, [])
  end
  assert_includes note, 'the has_many (tags.note_id) association can be neither "tags" nor "tags_as_note"'
end

test "a has_many through two foreign keys whose _as_<stem> name is taken falls back to the full column" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "users" do |t|
      t.string "name", null: false
      t.text "messages_as_sender"
    end
    s.create_table "messages" do |t|
      t.references :sender, foreign_key: false
      t.references :recipient, foreign_key: false
      t.text "body"
    end
    s.add_foreign_key "messages", "users", column: "sender_id"
    s.add_foreign_key "messages", "users", column: "recipient_id"
  end
  user = Cybertrain::Gen::ModelsEmitter.emit(definition.table("users"), definition, [])
  assert_lines(user, [
    '# has_many messages reads as messages_as_sender_id: "messages_as_sender" is a column, another association or a Cybertrain::Model method',
    'def messages_as_sender_id = MessageRelation.new("messages").where(sender_id: @id).to_a',
    'def messages_as_recipient = MessageRelation.new("messages").where(recipient_id: @id).to_a'
  ])
end

test "a has_many named like a belongs_to reader of the same model is renamed, not dropped" do
  # posts.comments_id (belongs_to `comments`) and comments.post_id (has_many
  # `comments`): both readers exist, the has_many as comments_as_post.
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "posts" do |t|
      t.string "title", null: false
      t.references :comments
    end
    s.create_table "comments" do |t|
      t.references :post
      t.string "body"
    end
  end
  post = Cybertrain::Gen::ModelsEmitter.emit(definition.table("posts"), definition, [])
  assert_lines(post, [
    "def comments = Comment.find_by(id: @comments_id)",
    '# has_many comments reads as comments_as_post: "comments" is a column, another association or a Cybertrain::Model method',
    'def comments_as_post = CommentRelation.new("comments").where(post_id: @id).to_a',
    "when :comments then self.comments",
    "when :comments_as_post then self.comments_as_post"
  ])
end

test "initial values: zero values for NOT NULL, nil for nullable, SQL defaults applied" do
  assert_lines(events_source, [
    '@name = "untitled"',
    '@seats = 10',
    '@rank = nil',
    '@level = Cybertrain::Cast.int_or_nil(3)',
    '@price = 0.0',
    '@ratio = Cybertrain::Cast.float_or_nil(0.5)',
    '@public = false',
    '@draft = Cybertrain::Cast.bool_or_nil(true)',
    '@starts_on = nil',
    '@published_at = nil',
    '@notes = nil'
  ])
end

test "string defaults are emitted as escaped Ruby literals" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "notes" do |t|
      t.string "title", null: false, default: %q('it''s "#{x}"')
    end
  end
  source = Cybertrain::Gen::ModelsEmitter.emit(definition.table("notes"), definition, [])
  assert_lines(source, ['@title = "it\'s \"\#{x}\""'])
end

test "a nullable foreign key and a foreign key to a differently named column" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "people" do |t|
      t.string "name", null: false
    end
    s.create_table "articles" do |t|
      t.references :editor, null: true, foreign_key: false
      t.integer "writer_id", null: false
    end
    s.add_foreign_key "articles", "people", column: "writer_id"
  end
  article = Cybertrain::Gen::ModelsEmitter.emit(definition.table("articles"), definition, [])
  assert_lines(article, [
    "def writer = Person.find_by(id: @writer_id)",
    "when :writer then self.writer",
    '@editor_id = Cybertrain::Cast.int_or_nil(row["editor_id"])'
  ])
  refute_line(article, "def editor = Editor.find_by(id: @editor_id)")
  person = Cybertrain::Gen::ModelsEmitter.emit(definition.table("people"), definition, [])
  assert_lines(person, [
    'def articles = ArticleRelation.new("articles").where(writer_id: @id).to_a',
    "when :articles then self.articles",
    "class PersonRelation < Cybertrain::Relation",
    'raise Cybertrain::RecordNotFound, "Couldn\'t find Person with id=#{id}" if rec.nil?'
  ])
end

test "two foreign keys to one table get distinct has_many names" do
  definition = Cybertrain::Schema.define(version: "1") do |s|
    s.create_table "users" do |t|
      t.string "name", null: false
    end
    s.create_table "messages" do |t|
      t.references :sender, foreign_key: false
      t.references :recipient, foreign_key: false
      t.text "body", null: false
    end
    s.create_table "posts" do |t|
      t.references :user
    end
    s.add_foreign_key "messages", "users", column: "sender_id"
    s.add_foreign_key "messages", "users", column: "recipient_id"
  end
  user = Cybertrain::Gen::ModelsEmitter.emit(definition.table("users"), definition, [])
  assert_lines(user, [
    'def messages_as_sender = MessageRelation.new("messages").where(sender_id: @id).to_a',
    'def messages_as_recipient = MessageRelation.new("messages").where(recipient_id: @id).to_a',
    'def posts = PostRelation.new("posts").where(user_id: @id).to_a',
    "when :messages_as_sender then self.messages_as_sender",
    "when :messages_as_recipient then self.messages_as_recipient",
    "when :posts then self.posts"
  ])
  refute_line(user, "when :messages then self.messages")
  message = Cybertrain::Gen::ModelsEmitter.emit(definition.table("messages"), definition, [])
  assert_lines(message, [
    "def sender = User.find_by(id: @sender_id)",
    "def recipient = User.find_by(id: @recipient_id)"
  ])
end

test "view methods that collide with columns or associations are skipped" do
  post = emit_for("posts", ["title", "comments", "summary", "published?"])
  assert_lines(post, ["when :summary then self.summary", "when :published? then self.published?"])
  refute_line(post, "when :title then self.title")
  assert_equal 1, post.lines.count { |l| l.strip == "when :comments then self.comments" }
end

# ---- ModelScan -------------------------------------------------------------

POST_MODEL_SOURCE = <<~'RUBY'
  # A user model file reopening the generated class.
  class Post < ApplicationRecord
    validates :title, presence: true
    before_save { |r| r.title = r.title.strip }

    def summary = title[0, 3]

    def self.recent = order("id DESC")

    def published?
      !created_at.nil?
    end

    def shout() = title.upcase
    def excerpt(n) = body.to_s[0, n]
    def label; "Post #{id}"; end
    def title=(v)
      @title = v
    end

    def ==(other) = super

    private

    def secret = "hidden"
  end
RUBY

test "scan_source finds the class name and arity-0 instance methods" do
  info = Cybertrain::Gen::ModelScan.scan_source("app/models/post.rb", POST_MODEL_SOURCE)
  assert_equal "Post", info.class_name
  assert_equal "app/models/post.rb", info.file
  assert_equal ["summary", "published?", "shout", "label"], info.view_methods
end

test "scan_source returns nil without a class line" do
  assert_nil Cybertrain::Gen::ModelScan.scan_source("x.rb", "# nothing here\nputs 1\n")
end

test "scan_source accepts a bare class reopening" do
  info = Cybertrain::Gen::ModelScan.scan_source("comment.rb", "class Comment\n  def short = body[0, 5]\nend\n")
  assert_equal "Comment", info.class_name
  assert_equal ["short"], info.view_methods
end

SINGLETON_MODEL_SOURCE = <<~'RUBY'
  class Post
    def summary = title[0, 3]

    class << self
      def recent
        order("id DESC")
      end

      def popular = where(featured: true)
    end

    class << self; def oneliner = 1; end

    def excerpt = body.to_s[0, 10]

    class Draft
      def unsaved = true
    end

    module Tags
      def tag_list = ""
    end

    def closing
      true
    end
  end

  class PostPresenter
    def headline = "x"
  end
RUBY

test "scan_source skips class << self, nested classes and later classes" do
  info = Cybertrain::Gen::ModelScan.scan_source("app/models/post.rb", SINGLETON_MODEL_SOURCE)
  assert_equal "Post", info.class_name
  assert_equal ["summary", "excerpt", "closing"], info.view_methods
end

test "scan_source inside a module stops at the class's own end" do
  source = "module Blog\n  class Post\n    def summary = 1\n  end\n\n  def helper = 2\nend\n"
  info = Cybertrain::Gen::ModelScan.scan_source("post.rb", source)
  assert_equal ["summary"], info.view_methods
end

test "view_methods_for picks the scanned methods of one model" do
  list = [
    Cybertrain::Gen::ModelInfo.new("comment.rb", "Comment", ["short"]),
    Cybertrain::Gen::ModelInfo.new("post.rb", "Post", ["summary"])
  ]
  assert_equal ["summary"], Cybertrain::Gen::ModelsEmitter.view_methods_for("Post", list)
  assert_equal [], Cybertrain::Gen::ModelsEmitter.view_methods_for("Tag", list)
end

test "outputs maps gen/models paths to sources for every table" do
  definition = model_spec_schema
  outputs = Cybertrain::Gen::ModelsEmitter.outputs(definition, [])
  assert_equal ["gen/models/comment.rb", "gen/models/flag.rb", "gen/models/post.rb"], outputs.keys
  assert_equal EXPECTED_COMMENT, outputs["gen/models/comment.rb"]
end

Cybertrain::Test.run!
