require "tmpdir"
require "cybertrain/test"
require "cybertrain/generator/migrations_emitter"
require "cybertrain/generator/runner"

FIXTURE = "test/fixtures/gen_app"

EXPECTED = <<~'RUBY'
  # Generated by `spin run gen`. Do not edit.
  require "cybertrain/migration"
  require_relative "../db/migrate/20260101000000_create_posts"
  Cybertrain::Migration.register("20260101000000", CreatePosts.new)
  require_relative "../db/migrate/20260101000100_create_comments"
  Cybertrain::Migration.register("20260101000100", CreateComments.new)
RUBY

test "emits a require_relative + register pair per migration file, sorted by version" do
  assert_equal EXPECTED, Cybertrain::Gen::MigrationsEmitter.emit(FIXTURE)
end

test "the fixture's checked-in gen/migrations.rb is what the emitter produces" do
  assert_equal EXPECTED, File.read("#{FIXTURE}/gen/migrations.rb")
end

test "migration_files lists db/migrate/*.rb sorted by file name" do
  files = Cybertrain::Gen::MigrationsEmitter.migration_files(FIXTURE)
  assert_equal [
    "#{FIXTURE}/db/migrate/20260101000000_create_posts.rb",
    "#{FIXTURE}/db/migrate/20260101000100_create_comments.rb"
  ], files
end

test "migration_files is empty when db/migrate does not exist" do
  assert_equal [], Cybertrain::Gen::MigrationsEmitter.migration_files("#{FIXTURE}/no_such_app")
end

test "version_of / name_of split the timestamp prefix" do
  assert_equal "20260101000000", Cybertrain::Gen::MigrationsEmitter.version_of("20260101000000_create_posts")
  assert_equal "create_posts", Cybertrain::Gen::MigrationsEmitter.name_of("20260101000000_create_posts")
end

# --- Runner integration: gen/migrations.rb is written only for an app tree
# that has a db/migrate directory, so a schema-less/migration-less fixture
# (like test/gen_manifest.rb's ROOT) keeps behaving exactly as before.

ROOT = Dir.mktmpdir("cybertrain-gen-migrations")

at_exit do
  files = [
    "gen/migrations.rb", "gen/routes.rb", "gen/controllers.rb", "gen/views.rb", "gen/app.rb",
    "db/migrate/20260101000000_create_posts.rb", "db/migrate/20260101000100_create_comments.rb"
  ]
  files.each { |f| File.delete("#{ROOT}/#{f}") if File.exist?("#{ROOT}/#{f}") }
  ["db/migrate", "db", "gen", "app/controllers", "app"].each do |d|
    Dir.rmdir("#{ROOT}/#{d}") if Dir.exist?("#{ROOT}/#{d}")
  end
  Dir.rmdir(ROOT)
end

Dir.mkdir("#{ROOT}/app")
Dir.mkdir("#{ROOT}/app/controllers")
Dir.mkdir("#{ROOT}/db")
Dir.mkdir("#{ROOT}/db/migrate")
File.write("#{ROOT}/db/migrate/20260101000000_create_posts.rb", "class CreatePosts; end\n")

def draw_empty_routes
  Cybertrain::Routes.reset!
  Cybertrain::Routes.draw {}
end

test "runner writes gen/migrations.rb when db/migrate exists" do
  draw_empty_routes
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, [])
  assert_equal Cybertrain::Gen::MigrationsEmitter.emit(ROOT), File.read("#{ROOT}/gen/migrations.rb")
end

test "runner --check is fresh once gen/migrations.rb is written" do
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
end

test "runner --check reports gen/migrations.rb stale after a new migration file appears" do
  File.write("#{ROOT}/db/migrate/20260101000100_create_comments.rb", "class CreateComments; end\n")
  assert_equal 1, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
  File.delete("#{ROOT}/db/migrate/20260101000100_create_comments.rb")
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
end

Cybertrain::Test.run!
