require "tmpdir"
require "cybertrain/test"
require "cybertrain/generator"

# A throwaway app tree with every kind of file the manifest lists.
ROOT = Dir.mktmpdir("cybertrain-gen")
TREE_DIRS = ["gen", "gen/models", "app", "app/models", "app/controllers", "app/controllers/admin", "app/helpers"]
TREE_FILES = [
  "gen/models/post.rb", "gen/models/comment.rb",
  "app/models/post.rb", "app/models/comment.rb",
  "app/controllers/posts_controller.rb", "app/controllers/application_controller.rb",
  "app/controllers/admin/users_controller.rb", "app/controllers/comments_controller.rb",
  "app/controllers/README.md",
  "app/helpers/posts_helper.rb", "app/helpers/application_helper.rb"
]
TREE_DIRS.each { |d| Dir.mkdir("#{ROOT}/#{d}") }
TREE_FILES.each do |f|
  name = Cybertrain::Inflector.camelize(f.delete_prefix("app/controllers/").delete_suffix(".rb"))
  parent = name == "ApplicationController" ? "Cybertrain::Controller" : "ApplicationController"
  File.write("#{ROOT}/#{f}", "class #{name} < #{parent}\nend\n")
end

GENERATED = ["gen/routes.rb", "gen/controllers.rb", "gen/app.rb"]

# Test.run! exits the process, so the tree is removed at exit.
at_exit do
  (TREE_FILES + GENERATED).each { |f| File.delete("#{ROOT}/#{f}") if File.exist?("#{ROOT}/#{f}") }
  TREE_DIRS.reverse.each { |d| Dir.rmdir("#{ROOT}/#{d}") }
  Dir.rmdir(ROOT)
end

def draw_routes
  Cybertrain::Routes.reset!
  Cybertrain::Routes.draw do
    resources :posts, only: [:index]
  end
end

test "manifest lists gen, then app models, controllers and helpers" do
  expected = <<~'RUBY'
    # Generated by `spin run gen`. Do not edit.
    require_relative "models/comment"
    require_relative "models/post"
    require_relative "routes"
    require_relative "controllers"
    require_relative "../app/models/comment"
    require_relative "../app/models/post"
    require_relative "../app/controllers/application_controller"
    require_relative "../app/controllers/admin/users_controller"
    require_relative "../app/controllers/comments_controller"
    require_relative "../app/controllers/posts_controller"
    require_relative "../app/helpers/application_helper"
    require_relative "../app/helpers/posts_helper"
  RUBY
  assert_equal expected, Cybertrain::Gen::Manifest.emit(ROOT)
end

test "manifest for the fixture app" do
  expected = <<~'RUBY'
    # Generated by `spin run gen`. Do not edit.
    require_relative "models/comment"
    require_relative "models/post"
    require_relative "routes"
    require_relative "controllers"
    require_relative "../app/models/post"
    require_relative "../app/controllers/application_controller"
    require_relative "../app/controllers/comments_controller"
    require_relative "../app/controllers/pages_controller"
    require_relative "../app/controllers/posts_controller"
  RUBY
  assert_equal expected, Cybertrain::Gen::Manifest.emit("test/fixtures/gen_app")
end

test "runner writes the three gen files" do
  draw_routes
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, [])
  assert_equal Cybertrain::Gen::Manifest.emit(ROOT), File.read("#{ROOT}/gen/app.rb")
  assert_equal Cybertrain::Gen::RoutesEmitter.emit(Cybertrain::Routes.specs), File.read("#{ROOT}/gen/routes.rb")
  controllers = File.read("#{ROOT}/gen/controllers.rb")
  assert_includes controllers, "class ApplicationController < Cybertrain::Controller\n"
  assert_includes controllers, "module Admin\n  class UsersController < ::ApplicationController\n"
end

test "runner leaves unchanged files alone" do
  draw_routes
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, [])
end

test "runner --check passes when gen is fresh" do
  draw_routes
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
end

test "runner --check reports stale files and writes nothing" do
  Cybertrain::Routes.reset!
  Cybertrain::Routes.draw { resources :posts, only: [:index, :show] }
  File.write("#{ROOT}/gen/app.rb", "# edited by hand\n")
  assert_equal 1, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
  assert_equal "# edited by hand\n", File.read("#{ROOT}/gen/app.rb")
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, [])
  assert_equal 0, Cybertrain::Gen::Runner.run(ROOT, ["--check"])
end

Cybertrain::Test.run!
