require "cybertrain/test"
require "cybertrain/generator"

POSTS_SOURCE = <<~'RUBY'
  class PostsController < ApplicationController
    before_action :set_post, only: [:show]
    rescue_from RecordNotFound, with: :nf

    def show
      @post ||= Post.first
      render plain: "same" if @post == @posts
    end

    def index
      @posts = Post.all
    end

    private

    def set_post
      @post = Post.find(params[:id])
      @post.title = "x"
    end
  end
RUBY

test "scan_source finds the class line, ivars and callbacks" do
  info = Cybertrain::Gen::ControllerScan.scan_source("app/controllers/posts_controller.rb", POSTS_SOURCE)
  assert_equal "app/controllers/posts_controller.rb", info.file
  assert_equal "PostsController", info.class_name
  assert_equal "ApplicationController", info.superclass_name
  assert_equal ["post", "posts"], info.ivars
  assert_equal ["set_post", "nf"], info.callbacks
end

test "ivars are unique in first-seen order and skip comparisons" do
  source = "class A < B\n  def x\n    @post = 1; @count += 1; @post ||= 2\n    @@total = 3\n    @done &&= true if @flag == 1 || @re =~ /x/\n    h = { @key => 1 }\n  end\nend\n"
  info = Cybertrain::Gen::ControllerScan.scan_source("a.rb", source)
  assert_equal ["post", "count", "done"], info.ivars
end

test "every target of a multiple assignment is an ivar" do
  source = "class A < B\n  def x\n    @a, @b = 1, 2\n    first, @c, *@rest = list; @d = 4\n    each { |k, v| k }\n  end\n  def y(a, b = @e)\n  end\nend\n"
  info = Cybertrain::Gen::ControllerScan.scan_source("a.rb", source)
  assert_equal ["a", "b", "c", "rest", "d"], info.ivars
end

test "commented lines are ignored" do
  source = "class A < B\n  # @secret = 1\n  # before_action :hidden\n  @shown = 1\nend\n"
  info = Cybertrain::Gen::ControllerScan.scan_source("a.rb", source)
  assert_equal ["shown"], info.ivars
  assert_equal [], info.callbacks
end

test "callbacks: several symbols, all three kinds, rescue_from with:" do
  source = <<~'RUBY'
    class AdminController < ApplicationController
      before_action :authenticate, :admin?, except: [:index]
      after_action(:log_access)
      around_action :timed
      before_action(only: [:show]) { |c| c.set_thing }
      skip_it :nope
      rescue_from(Forbidden, with: :deny)
      rescue_from(Gone) { |c, e| c.head :not_found }
    end
  RUBY
  info = Cybertrain::Gen::ControllerScan.scan_source("admin_controller.rb", source)
  assert_equal ["authenticate", "admin?", "log_access", "timed", "deny"], info.callbacks
end

test "a file without a class line scans to nil" do
  assert_nil Cybertrain::Gen::ControllerScan.scan_source("x.rb", "module Helpers\nend\n")
end

test "the class named after the file wins" do
  source = "class NotFound < StandardError\nend\n\nclass ApplicationController < Cybertrain::Controller\nend\n"
  info = Cybertrain::Gen::ControllerScan.scan_source("app/controllers/application_controller.rb", source)
  assert_equal "ApplicationController", info.class_name
  assert_equal "Cybertrain::Controller", info.superclass_name
  other = Cybertrain::Gen::ControllerScan.scan_source("misc.rb", source)
  assert_equal "NotFound", other.class_name
end

test "scan_dir reads every controller sorted by file" do
  infos = Cybertrain::Gen::ControllerScan.scan_dir("test/fixtures/gen_app/app/controllers")
  assert_equal ["ApplicationController", "CommentsController", "PagesController", "PostsController"], infos.map { |i| i.class_name }
  assert_equal "test/fixtures/gen_app/app/controllers/posts_controller.rb", infos.last.file
  assert_equal ["set_post", "stamp"], infos.last.callbacks
  assert_equal [], Cybertrain::Gen::ControllerScan.scan_dir("test/fixtures/gen_app/no_such_dir")
end

test "emit writes view_assigns and run_callback per controller" do
  infos = [Cybertrain::Gen::ControllerScan.scan_source("app/controllers/posts_controller.rb", POSTS_SOURCE)]
  expected = <<~'RUBY'
    # Generated by `spin run gen` from app/controllers. Do not edit.

    class PostsController < ApplicationController
      def view_assigns
        { "post" => @post, "posts" => @posts }
      end

      def run_callback(name)
        case name
        when :set_post then set_post
        when :nf then nf
        else super
        end
      end
    end
  RUBY
  assert_equal expected, Cybertrain::Gen::ControllersEmitter.emit(infos)
end

test "emit puts parents first and inherits their ivars" do
  child = Cybertrain::Gen::ControllerScan.scan_source("admin_controller.rb", "class AdminController < ApplicationController\n  def index\n    @users = []\n  end\nend\n")
  parent = Cybertrain::Gen::ControllerScan.scan_source("application_controller.rb", "class ApplicationController < Cybertrain::Controller\n  before_action :load_user\n  def load_user\n    @user = 1\n  end\nend\n")
  bare = Cybertrain::Gen::ControllerScan.scan_source("health_controller.rb", "class HealthController < Cybertrain::Controller\nend\n")
  expected = <<~'RUBY'
    # Generated by `spin run gen` from app/controllers. Do not edit.

    class ApplicationController < Cybertrain::Controller
      def view_assigns
        { "user" => @user }
      end

      def run_callback(name)
        case name
        when :load_user then load_user
        else super
        end
      end
    end

    class HealthController < Cybertrain::Controller
      def view_assigns
        {}
      end
    end

    class AdminController < ApplicationController
      def view_assigns
        { "user" => @user, "users" => @users }
      end
    end
  RUBY
  assert_equal expected, Cybertrain::Gen::ControllersEmitter.emit([child, parent, bare])
end

test "a namespaced controller is emitted inside its modules" do
  info = Cybertrain::Gen::ControllerScan.scan_source("app/controllers/admin/users_controller.rb", "class Admin::UsersController < ApplicationController\n  before_action :require_admin\n  def index\n    @users = []\n  end\nend\n")
  deep = Cybertrain::Gen::ControllerScan.scan_source("app/controllers/api/v1/items_controller.rb", "class Api::V1::ItemsController < Api::BaseController\nend\n")
  expected = <<~'RUBY'
    # Generated by `spin run gen` from app/controllers. Do not edit.

    module Admin
      class UsersController < ::ApplicationController
        def view_assigns
          { "users" => @users }
        end

        def run_callback(name)
          case name
          when :require_admin then require_admin
          else super
          end
        end
      end
    end

    module Api
      module V1
        class ItemsController < ::Api::BaseController
          def view_assigns
            {}
          end
        end
      end
    end
  RUBY
  assert_equal expected, Cybertrain::Gen::ControllersEmitter.emit([info, deep])
end

Cybertrain::Test.run!
