require "cybertrain/generator/controller_scan"

module Cybertrain
  module Gen
    # Writes gen/controllers.rb: per controller, view_assigns (the ivars a
    # template can read, including those its scanned parents assign) and a
    # run_callback case table so symbol callbacks dispatch without send.
    module ControllersEmitter
      def self.emit(infos)
        out = +"# Generated by `spin run gen` from app/controllers. Do not edit.\n"
        parents_first(infos).each do |info|
          out << "\n"
          out << class_source(info, visible_ivars(info, infos))
        end
        out
      end

      # A namespaced controller (Admin::UsersController) is written inside
      # `module Admin`, because gen/controllers.rb loads before any app file
      # could define the module. Its superclass came from a compact
      # `class Admin::UsersController < ApplicationController` line, which
      # resolves constants from the top level, so it is emitted as
      # `::ApplicationController` to keep that meaning inside the modules.
      def self.class_source(info, ivars)
        parts = info.class_name.split("::")
        return plain_class_source(info.class_name, info.superclass_name, info.callbacks, ivars) if parts.size < 2

        superclass = info.superclass_name
        superclass = "::#{superclass}" unless superclass.start_with?("::")
        body = plain_class_source(parts.last.to_s, superclass, info.callbacks, ivars)
        out = +""
        depth = 0
        parts.each_with_index do |mod, i|
          next if i == parts.size - 1

          out << ("  " * depth) << "module #{mod}\n"
          depth += 1
        end
        body.each_line do |line|
          out << ("  " * depth) unless line == "\n"
          out << line
        end
        while depth > 0
          depth -= 1
          out << ("  " * depth) << "end\n"
        end
        out
      end

      def self.plain_class_source(class_name, superclass_name, callbacks, ivars)
        out = +""
        out << "class #{class_name} < #{superclass_name}\n"
        out << "  def view_assigns\n"
        out << "    #{hash_source(ivars)}\n"
        out << "  end\n"
        unless callbacks.empty?
          out << "\n"
          out << "  def run_callback(name)\n"
          out << "    case name\n"
          callbacks.each { |n| out << "    when :#{n} then #{n}\n" }
          out << "    else super\n"
          out << "    end\n"
          out << "  end\n"
        end
        out << "end\n"
        out
      end

      # { "post" => @post, "posts" => @posts }
      def self.hash_source(ivars)
        return "{}" if ivars.empty?

        "{ " + ivars.map { |n| "\"#{n}\" => @#{n}" }.join(", ") + " }"
      end

      # The class's own ivars after those of its scanned ancestors.
      def self.visible_ivars(info, infos)
        chain = []
        current = info
        until current.nil? || chain.include?(current.class_name)
          chain.unshift(current.class_name)
          current = find(infos, current.superclass_name)
        end
        names = []
        chain.each do |class_name|
          find(infos, class_name).ivars.each { |n| names << n unless names.include?(n) }
        end
        names
      end

      def self.find(infos, class_name)
        infos.each { |i| return i if i.class_name == class_name }
        nil
      end

      # Keeps file order but moves each class after its superclass, so the
      # file is loadable top to bottom (CRuby needs the superclass defined).
      def self.parents_first(infos)
        pending = infos.dup
        ordered = []
        until pending.empty?
          ready = pending.select { |i| find(pending, i.superclass_name).nil? }
          ready = pending.dup if ready.empty?   # a cycle: give up on ordering
          ready.each do |i|
            ordered << i
            pending.delete(i)
          end
        end
        ordered
      end
    end
  end
end
