require "cybertrain/generator/controller_scan"

module Cybertrain
  module Gen
    # Writes gen/app.rb, the one file an app's binaries require to load
    # everything: generated models, routes and controllers, then the app's
    # own models, controllers (application_controller first) and helpers.
    module Manifest
      def self.emit(root)
        emit_with_models(root, rb_files(root, "gen/models"))
      end

      # The same manifest, listing `model_files` ("gen/models/post", sorted)
      # instead of whatever gen/models holds on disk: Runner passes the
      # files the schema calls for, so --check sees a manifest change for a
      # table that was added or dropped before gen/models is rewritten.
      def self.emit_with_models(root, model_files)
        lines = []
        model_files.each { |f| lines << f.delete_prefix("gen/") }
        lines << "routes"
        lines << "controllers"
        rb_files(root, "app/models").each { |f| lines << "../#{f}" }
        controllers = rb_files(root, "app/controllers")
        first = "app/controllers/application_controller"
        lines << "../#{first}" if controllers.include?(first)
        controllers.each { |f| lines << "../#{f}" unless f == first }
        rb_files(root, "app/helpers").each { |f| lines << "../#{f}" }

        out = +"# Generated by `spin run gen`. Do not edit.\n"
        lines.each { |l| out << "require_relative \"#{l}\"\n" }
        out
      end

      # "app/models/post" for root/app/models/post.rb, sorted.
      def self.rb_files(root, dir)
        base = "#{root}/"
        ControllerScan.ruby_files("#{root}/#{dir}").map do |path|
          rel = path.start_with?(base) ? path[base.size, path.size - base.size].to_s : path
          rel.delete_suffix(".rb")
        end
      end
    end
  end
end
