require "cybertrain/generator/controller_scan"
require "cybertrain/generator/inflector"

module Cybertrain
  module Gen
    # Cybertrain::Gen::MigrationsEmitter -- writes gen/migrations.rb: one
    # `require_relative` + `Cybertrain::Migration.register` pair per
    # db/migrate/<version>_<name>.rb file, sorted by file name (a fixed-width
    # numeric timestamp prefix, so name order is version order).
    module MigrationsEmitter
      def self.emit(root)
        buf = +"# Generated by `spin run gen`. Do not edit.\n"
        buf << "require \"cybertrain/migration\"\n"
        migration_files(root).each do |path|
          base = File.basename(path, ".rb")
          version = version_of(base)
          class_name = Inflector.camelize(name_of(base))
          buf << "require_relative \"../db/migrate/#{base}\"\n"
          buf << "Cybertrain::Migration.register(\"#{version}\", #{class_name}.new)\n"
        end
        buf
      end

      # Sorted "<version>_<name>.rb" paths under root/db/migrate ([] when the
      # directory does not exist).
      def self.migration_files(root)
        ControllerScan.ruby_files("#{root}/db/migrate")
      end

      # "20260101000000_create_posts" -> "20260101000000".
      def self.version_of(base)
        i = base.index("_")
        i.nil? ? base : base[0, i]
      end

      # "20260101000000_create_posts" -> "create_posts".
      def self.name_of(base)
        i = base.index("_")
        i.nil? ? base : base[i + 1, base.length - i - 1]
      end
    end
  end
end
