require "cybertrain/schema"
require "cybertrain/generator/inflector"
require "cybertrain/generator/model_scan"

module Cybertrain
  module Gen
    # Emits gen/models/<model>.rb for each table of db/schema.rb: a typed
    # `<Model>Relation` and a `<Model> < Cybertrain::Model` whose ivars,
    # casts, finders and associations are spelled out as plain Ruby, because
    # Spinel cannot define methods at runtime. test/model.rb hand-writes
    # this exact shape and is its executable specification.
    module ModelsEmitter
      # Column names the emitter refuses (besides anything not matching
      # COLUMN_NAME_PATTERN and the Ruby keywords below): each would define
      # an attribute reader/writer that shadows a method of Cybertrain::Model
      # or Object that the framework itself calls (`errors`, `save`,
      # `attributes`, `hash`, `send`, ...), or one that breaks the generated
      # source (`class`). `id` is deliberately absent: the primary key is
      # handled by Model#id. cli/scaffold.rb keeps its own, narrower
      # RESERVED_COLUMNS (id created_at updated_at) for what a scaffold may
      # add; this list is about what the generated class can host.
      RESERVED_COLUMN_NAMES = [
        "errors", "persisted", "class", "hash", "object_id", "send", "freeze",
        "display", "method", "instance_variable_get", "attributes", "save",
        "update", "destroy", "reload", "valid?", "model_name", "new_record",
        "to_json", "as_json", "to_param", "to_row", "load_row", "set_id",
        "run_callbacks", "insert_row", "update_row", "read_attribute",
        "write_attribute", "assign_attributes", "read_association",
        "call_view_method", "initialize", "table_name", "column_names",
        "from_row", "dup", "clone", "tap", "itself", "extend", "inspect",
        "to_s", "public_send", "respond_to", "instance_variable_set",
        "instance_variables", "instance_of", "kind_of", "is_a", "frozen"
      ]

      # Ruby keywords: `def end=` / `attr_reader :class` would not parse or
      # would redefine core behaviour.
      RUBY_KEYWORD_NAMES = [
        "__ENCODING__", "__LINE__", "__FILE__", "BEGIN", "END", "alias", "and",
        "begin", "break", "case", "class", "def", "defined", "do", "else",
        "elsif", "end", "ensure", "false", "for", "if", "in", "module", "next",
        "nil", "not", "or", "redo", "rescue", "retry", "return", "self",
        "super", "then", "true", "undef", "unless", "until", "when", "while",
        "yield"
      ]

      # "posts" -> "Post"; "blog_posts" -> "BlogPost".
      def self.model_class_name(table)
        Inflector.camelize(Inflector.singularize(table.to_s))
      end

      # "posts" -> "post.rb".
      def self.file_name(table)
        Inflector.singularize(table.to_s) + ".rb"
      end

      # The view methods ModelScan found for `class_name` (empty when its
      # app/models file is missing or defines none).
      def self.view_methods_for(class_name, infos)
        infos.each { |info| return info.view_methods if info.class_name == class_name }
        Array.new(0) { "" }
      end

      # { "gen/models/post.rb" => source, ... } for every table, by table name.
      def self.outputs(definition, infos)
        out = { "" => "" }
        out.delete("")
        definition.tables.each do |table|
          methods = view_methods_for(model_class_name(table.name), infos)
          out["gen/models/" + file_name(table.name)] = emit(table, definition, methods)
        end
        out
      end

      # Writes every gen/models file under `root`; returns the relative paths.
      # (Gen::Runner does not use this: it goes through `outputs` + sync_file
      # so unchanged files keep their mtime and --check works. Kept for
      # test/gen_models_compiles.rb.)
      def self.write_all(root, definition, infos)
        Dir.mkdir(root + "/gen") unless Dir.exist?(root + "/gen")
        Dir.mkdir(root + "/gen/models") unless Dir.exist?(root + "/gen/models")
        written = Array.new(0) { "" }
        outputs(definition, infos).each do |path, source|
          File.write(root + "/" + path, source)
          written << path
        end
        written
      end

      def self.emit(table, definition, view_methods)
        raise ArgumentError, "table #{table.name} has no columns" if table.columns.empty?

        check_column_names(table)
        model = model_class_name(table.name)
        # Each part builds and returns its own String: a String argument
        # appended to inside the callee does not reliably update the
        # caller's copy under Spinel (`<<` may reallocate the buffer).
        src = +"# Generated by `spin run gen` from db/schema.rb. Do not edit.\n"
        src << emit_relation(model)
        src << "\n"
        src << emit_model_head(model, table)
        src << emit_persistence(model, table)
        src << emit_dispatch(table, definition, view_methods)
        src << "end\n"
        src
      end

      # Raises ArgumentError (the generator exits non-zero) for a column the
      # generated class cannot host: not a plain snake_case identifier, a Ruby
      # keyword, or one of RESERVED_COLUMN_NAMES.
      def self.check_column_names(table)
        table.columns.each do |c|
          name = c.name
          unless column_name_valid?(name)
            raise ArgumentError, "table #{table.name}: column #{name.inspect} is not a valid attribute name " \
                                 "(use lowercase letters, digits and _, not starting with a digit)"
          end
          if RUBY_KEYWORD_NAMES.include?(name) || RESERVED_COLUMN_NAMES.include?(name)
            raise ArgumentError, "table #{table.name}: column #{name.inspect} is reserved " \
                                 "(it would shadow a method of Cybertrain::Model or Object); rename it"
          end
        end
        nil
      end

      # /\A[a-z_][a-z0-9_]*\z/ spelled out so Spinel needs no Regexp here.
      def self.column_name_valid?(name)
        return false if name.empty?

        i = 0
        name.each_char do |ch|
          lower = ch >= "a" && ch <= "z"
          digit = ch >= "0" && ch <= "9"
          return false unless lower || ch == "_" || (digit && i > 0)

          i += 1
        end
        true
      end

      def self.emit_relation(model)
        src = +""
        src << "class #{model}Relation < Cybertrain::Relation\n"
        src << "  def where(h) = (add_where(h); self)\n"
        src << "  def where_sql(s, b = []) = (add_where_sql(s, b); self)\n"
        src << "  def order(o) = (set_order(o); self)\n"
        src << "  def order_sql(s) = (add_order_sql(s); self)\n"
        src << "  def limit(n) = (set_limit(n); self)\n"
        src << "  def offset(n) = (set_offset(n); self)\n"
        src << "\n"
        src << "  def to_a\n"
        src << "    out = Array.new(0) { #{model}.new }\n"
        src << "    rows.each { |r| out << #{model}.from_row(r) }\n"
        src << "    out\n"
        src << "  end\n"
        src << "\n"
        src << "  def each(&blk) = to_a.each(&blk)\n"
        src << "\n"
        src << "  def first\n"
        src << "    r = first_row\n"
        src << "    return nil if r.nil?\n"
        src << "    #{model}.from_row(r)\n"
        src << "  end\n"
        src << "\n"
        src << "  def last\n"
        src << "    r = last_row\n"
        src << "    return nil if r.nil?\n"
        src << "    #{model}.from_row(r)\n"
        src << "  end\n"
        src << "\n"
        src << "  def find_by(h) = where(h).first\n"
        src << "\n"
        src << "  def find(id)\n"
        src << "    rec = where(id: id).first\n"
        src << "    raise Cybertrain::RecordNotFound, \"Couldn't find #{model} with id=\#{id}\" if rec.nil?\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src << "  def size = count\n"
        src << "end\n"
        src
      end

      def self.emit_model_head(model, table)
        src = +""
        names = table.columns.map { |c| c.name }
        quoted = names.map { |n| "\"#{n}\"" }.join(", ")
        symbols = names.map { |n| ":#{n}" }.join(", ")
        src << "class #{model} < Cybertrain::Model\n"
        src << "  def self.table_name = \"#{table.name}\"\n"
        src << "  def self.column_names = [\"id\", #{quoted}]\n"
        src << "  def model_name = \"#{model}\"\n"
        src << "\n"
        # Readers only. Every writer casts like write_attribute does (rule
        # 7: a nullable ivar is assigned only through a Cast helper that can
        # return nil, e.g. time_or_nil; a raw attr_writer would store a Time
        # straight into the nil-initialised ivar). The writers return nil so
        # a name shared by two models (`body=`) has one return type (rule 34);
        # `rec.body = v` still evaluates to v at the call site.
        src << "  attr_reader #{symbols}\n"
        src << "\n"
        table.columns.each do |c|
          src << "  def #{c.name}=(v)\n"
          src << "    @#{c.name} = Cybertrain::Cast.#{cast_for(c)}(v)\n"
          src << "    nil\n"
          src << "  end\n"
        end
        src << "\n"
        src << "  def initialize(attrs = {})\n"
        src << "    super()\n"
        table.columns.each { |c| src << "    @#{c.name} = #{initial_value(c)}\n" }
        src << "    assign_attributes(attrs)\n"
        src << "  end\n"
        src << "\n"
        src << "  def self.from_row(row)\n"
        src << "    rec = #{model}.new\n"
        src << "    rec.load_row(row)\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src << "  def load_row(row)\n"
        src << "    set_id(Cybertrain::Cast.int(row[\"id\"]))\n"
        table.columns.each { |c| src << "    @#{c.name} = Cybertrain::Cast.#{cast_for(c)}(row[\"#{c.name}\"])\n" }
        src << "    mark_persisted!\n"
        src << "    nil\n"
        src << "  end\n"
        src << "\n"
        src << "  def read_attribute(name)\n"
        src << "    case name\n"
        src << "    when :id then @id\n"
        table.columns.each { |c| src << "    when :#{c.name} then @#{c.name}\n" }
        src << "    else nil\n"
        src << "    end\n"
        src << "  end\n"
        src << "\n"
        src << "  def write_attribute(name, value)\n"
        src << "    case name\n"
        # Through the typed writers above, so the two cannot drift apart.
        table.columns.each { |c| src << "    when :#{c.name} then self.#{c.name} = value\n" }
        src << "    end\n"
        src << "    nil\n"
        src << "  end\n"
        src << "\n"
        src << "  def assign_attributes(attrs)\n"
        src << "    attrs.each { |k, v| write_attribute(k.to_s.to_sym, v) }\n"
        src << "    self\n"
        src << "  end\n"
        src << "\n"
        src << "  def to_row\n"
        src << "    {\n"
        pairs = table.columns.map { |c| "      \"#{c.name}\" => Cybertrain::Cast.to_sql(@#{c.name})" }.join(",\n")
        src << "#{pairs}\n"
        src << "    }\n"
        src << "  end\n"
        src << "\n"
        src
      end

      def self.emit_persistence(model, table)
        src = +""
        src << "  def self.all = #{model}Relation.new(\"#{table.name}\")\n"
        src << "  def self.where(h) = all.where(h)\n"
        src << "  def self.order(o) = all.order(o)\n"
        src << "  def self.limit(n) = all.limit(n)\n"
        src << "  def self.find(id) = all.find(id)\n"
        src << "  def self.find_by(h) = all.find_by(h)\n"
        src << "  def self.first = all.first\n"
        src << "  def self.last = all.last\n"
        src << "  def self.count = all.count\n"
        src << "\n"
        src << "  def self.create(attrs = {})\n"
        src << "    rec = #{model}.new(attrs)\n"
        src << "    rec.save\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src
      end

      # Associations, then the read_association / call_view_method case
      # tables the template interpreter dispatches through by name.
      def self.emit_dispatch(table, definition, view_methods)
        src = +""
        taken = table.columns.map { |c| c.name }
        taken << "id"
        assoc_names = Array.new(0) { "" }
        assoc_defs = Array.new(0) { "" }

        # belongs_to: comments.post_id -> def post
        table.foreign_keys.each do |fk|
          col = fk.column
          next unless col.end_with?("_id") && !table.column(col).nil?

          name = col[0, col.size - 3]
          next if taken.include?(name) || assoc_names.include?(name)

          assoc_names << name
          assoc_defs << "def #{name} = #{model_class_name(fk.to_table)}.find_by(id: @#{col})"
        end

        # has_many: another table's foreign key pointing here -> def comments.
        # When that table points here through more than one column
        # (messages.sender_id and messages.recipient_id both -> users), each
        # gets its own name, `<table>_as_<column stem>` (def messages_as_sender,
        # def messages_as_recipient), so no key is dropped and the names do
        # not depend on declaration order.
        definition.tables.each do |other|
          next if other.name == table.name

          pointing = other.foreign_keys.select { |fk| fk.to_table == table.name }
          pointing.each do |fk|
            name = pointing.size > 1 ? other.name + "_as_" + column_stem(fk.column) : other.name
            next if taken.include?(name) || assoc_names.include?(name)

            assoc_names << name
            assoc_defs << "def #{name} = #{model_class_name(other.name)}Relation.new(\"#{other.name}\")" \
                          ".where(#{fk.column}: @id).to_a"
          end
        end

        methods = Array.new(0) { "" }
        view_methods.each do |m|
          next if taken.include?(m) || assoc_names.include?(m) || methods.include?(m)

          methods << m
        end

        unless assoc_defs.empty?
          assoc_defs.each { |d| src << "  #{d}\n" }
          src << "\n"
        end
        src << emit_case("read_association", assoc_names)
        src << "\n" unless assoc_names.empty? && methods.empty?
        src << emit_case("call_view_method", methods)
        src
      end

      # "sender_id" -> "sender"; a column without the suffix is its own stem.
      def self.column_stem(column)
        column.end_with?("_id") ? column[0, column.size - 3] : column
      end

      # A `case name` over `names`; a one-line `nil` stub when there are
      # none, since a `case` without any `when` does not parse.
      def self.emit_case(method, names)
        src = +""
        if names.empty?
          src << "  def #{method}(name) = nil\n"
          return src
        end
        src << "  def #{method}(name)\n"
        src << "    case name\n"
        names.each { |n| src << "    when :#{n} then #{n}\n" }
        src << "    else nil\n"
        src << "    end\n"
        src << "  end\n"
        src
      end

      # The Cast helper that reads and writes this column (spikes/NOTES.md
      # rule 7: Time ivars always go through time_or_nil).
      def self.cast_for(column)
        null = column.null
        case column.type
        when :integer then null ? "int_or_nil" : "int"
        when :float then null ? "float_or_nil" : "float"
        when :boolean then null ? "bool_or_nil" : "bool"
        when :datetime then "time_or_nil"
        when :date then "str_or_nil"
        else null ? "str_or_nil" : "str"
        end
      end

      # The ivar's value in `initialize`: the column's SQL default when it
      # has a simple one (INSERT writes every column, so the database's own
      # DEFAULT never applies), else "" / 0 / 0.0 / false for NOT NULL
      # columns and nil for nullable ones. Nullable columns with a default
      # still go through their Cast helper to keep the ivar's nullable type.
      def self.initial_value(column)
        return "nil" if column.type == :datetime || column.type == :date

        literal = default_literal(column)
        if column.null
          literal == "" ? "nil" : "Cybertrain::Cast.#{cast_for(column)}(#{literal})"
        elsif literal != ""
          literal
        else
          case column.type
          when :integer then "0"
          when :float then "0.0"
          when :boolean then "false"
          else "\"\""
          end
        end
      end

      # The Ruby literal for a column's SQL default text ("0", "'x'",
      # "false"), or "" when there is none or it is not a plain literal.
      def self.default_literal(column)
        raw = column.default
        return "" if raw.nil?

        text = raw.strip
        return "" if text.upcase == "NULL"

        case column.type
        when :integer
          integer_text?(text) ? text : ""
        when :float
          if integer_text?(text)
            text + ".0"
          elsif float_text?(text)
            text
          else
            ""
          end
        when :boolean
          if text == "true" || text == "TRUE" || text == "1" || text == "'t'"
            "true"
          elsif text == "false" || text == "FALSE" || text == "0" || text == "'f'"
            "false"
          else
            ""
          end
        when :string, :text
          quoted_sql?(text) ? ruby_string(text[1, text.size - 2].gsub("''", "'")) : ""
        else
          ""
        end
      end

      def self.integer_text?(text)
        digits = text.start_with?("-") ? text[1, text.size - 1] : text
        return false if digits == ""

        digits.each_char { |ch| return false unless ch >= "0" && ch <= "9" }
        true
      end

      def self.float_text?(text)
        dot = text.index(".")
        return false if dot.nil?

        integer_text?(text[0, dot]) && integer_text?("0" + text[dot + 1, text.size - dot - 1])
      end

      def self.quoted_sql?(text)
        text.size >= 2 && text.start_with?("'") && text.end_with?("'")
      end

      # A double-quoted Ruby literal for `str`, with `#{` / `#$` / `#@`
      # escaped so the generated file never interpolates.
      def self.ruby_string(str)
        out = +"\""
        chars = str.chars
        chars.each_with_index do |ch, i|
          nxt = i + 1 < chars.size ? chars[i + 1] : ""
          if ch == "\\"
            out << "\\\\"
          elsif ch == "\""
            out << "\\\""
          elsif ch == "\n"
            out << "\\n"
          elsif ch == "#" && (nxt == "{" || nxt == "$" || nxt == "@")
            out << "\\#"
          else
            out << ch
          end
        end
        out << "\""
        out
      end
    end
  end
end
