require "cybertrain/schema"
require "cybertrain/generator/inflector"
require "cybertrain/ident"
require "cybertrain/generator/model_scan"

module Cybertrain
  module Gen
    # Emits gen/models/<model>.rb for each table of db/schema.rb: a typed
    # `<Model>Relation` and a `<Model> < Cybertrain::Model` whose ivars,
    # casts, finders and associations are spelled out as plain Ruby, because
    # Spinel cannot define methods at runtime. test/model.rb hand-writes
    # this exact shape and is its executable specification.
    module ModelsEmitter
      # "posts" -> "Post"; "blog_posts" -> "BlogPost".
      def self.model_class_name(table)
        Inflector.camelize(Inflector.singularize(table.to_s))
      end

      # "posts" -> "post.rb".
      def self.file_name(table)
        Inflector.singularize(table.to_s) + ".rb"
      end

      # The view methods ModelScan found for `class_name` (empty when its
      # app/models file is missing or defines none).
      def self.view_methods_for(class_name, infos)
        infos.each { |info| return info.view_methods if info.class_name == class_name }
        Array.new(0) { "" }
      end

      # { "gen/models/post.rb" => source, ... } for every table, by table name.
      def self.outputs(definition, infos)
        out = { "" => "" }
        out.delete("")
        definition.tables.each do |table|
          methods = view_methods_for(model_class_name(table.name), infos)
          out["gen/models/" + file_name(table.name)] = emit(table, definition, methods)
        end
        out
      end

      # Writes every gen/models file under `root`; returns the relative paths.
      # (Gen::Runner does not use this: it goes through `outputs` + sync_file
      # so unchanged files keep their mtime and --check works. Kept for
      # test/gen_models_compiles.rb.)
      def self.write_all(root, definition, infos)
        Dir.mkdir(root + "/gen") unless Dir.exist?(root + "/gen")
        Dir.mkdir(root + "/gen/models") unless Dir.exist?(root + "/gen/models")
        written = Array.new(0) { "" }
        outputs(definition, infos).each do |path, source|
          File.write(root + "/" + path, source)
          written << path
        end
        written
      end

      def self.emit(table, definition, view_methods)
        raise ArgumentError, "table #{table.name} has no columns" if table.columns.empty?

        check_column_names(table)
        model = model_class_name(table.name)
        # Each part builds and returns its own String: a String argument
        # appended to inside the callee does not reliably update the
        # caller's copy under Spinel (`<<` may reallocate the buffer).
        src = +"# Generated by `spin run gen` from db/schema.rb. Do not edit.\n"
        src << emit_relation(model)
        src << "\n"
        src << emit_model_head(model, table)
        src << emit_persistence(model, table)
        src << emit_dispatch(table, definition, view_methods)
        src << "end\n"
        src
      end

      # The Ruby name a column's reader, writer and ivar carry: the column's
      # own name, except for Ident::RESERVED_COLUMN_NAMES and Ruby keywords
      # (Ident::RUBY_KEYWORDS), which take `<column>_column`. This is the one
      # place that decides it. A reader named `errors`, `save`, `hash` or
      # `to_ary` would shadow a method of Cybertrain::Model or Object that
      # the framework (or Ruby itself) calls on the record, and an ivar named
      # `@errors` / `@persisted` is one the Model owns; a keyword column
      # (`end`, `begin`, `class`) would need `def class` / `@class`, which is
      # not a shape worth supporting. All of them are renamed; everything
      # keyed by the column's SQL name (column_names, to_row, load_row,
      # params) stays keyed by it; read_attribute / write_attribute answer
      # both spellings (attribute_keys), so a template, which reaches a column
      # through read_attribute, can always use the Ruby name. The query API
      # (Relation#where / order / find_by, order_sql) does not: Relation is
      # built from a table name and knows no per-model rename table, and a
      # column is its SQL name there, so `Post.where(hash: 1)` is right and
      # `Post.where(hash_column: 1)` is "no such column". The Ruby name is the
      # reader, the writer, the constructor key and the template name only
      # (rename_note says so beside the accessor). An existing
      # schema must keep generating on upgrade, so such a column is renamed
      # rather than refused (`cybertrain generate scaffold` still refuses to
      # invent one).
      def self.reader_name(column_name)
        renamed?(column_name) ? column_name + "_column" : column_name
      end

      # Whether reader_name renames the column.
      def self.renamed?(column_name)
        Ident.reserved_column?(column_name) || Ident.keyword?(column_name)
      end

      # The ivar behind reader_name.
      def self.ivar_name(column_name)
        "@" + reader_name(column_name)
      end

      # The `when` keys of read_attribute / write_attribute for a column: its
      # SQL name, plus the reader's name when reader_name renamed it (the
      # query API takes the SQL name only: see reader_name). The
      # interpreter resolves `post.hash_column` through read_attribute and
      # knows no other way to the column, so without the second key a renamed
      # column would be unreachable from a template under its Ruby name. A
      # multi-value `when` is plain Ruby the interpreter already uses
      # (`when :size, :length`). A column that is not renamed keeps its single
      # key, so the committed models do not change.
      def self.attribute_keys(column_name)
        key = ":" + column_name
        reader_name(column_name) == column_name ? key : key + ", :" + reader_name(column_name)
      end

      # Raises ArgumentError (the generator exits non-zero) for a column the
      # generated class cannot host: not an ASCII Ruby method name
      # (Ident.column?: `[A-Za-z_][A-Za-z0-9_]*`), or one whose fallback
      # `<column>_column` another column already owns. A reserved name or a
      # keyword alone is not an error (reader_name renames it), and a column
      # named like another Object method (Ident::SHADOWING_COLUMN_NAMES,
      # `display`, `tap`) is accepted with a note in the generated file: an
      # existing schema must keep generating. `cybertrain generate scaffold`
      # is stricter (and wants snake_case): it refuses keywords, reserved and
      # shadowing names before it writes any file, since it invents them.
      def self.check_column_names(table)
        names = table.columns.map { |c| c.name }
        table.columns.each do |c|
          name = c.name
          unless Ident.column?(name)
            raise ArgumentError, "table #{table.name}: column #{name.inspect} is not a valid attribute name " \
                                 "(a column name is an ASCII identifier: ASCII letters, digits and _, " \
                                 "not starting with a digit)"
          end
          next unless renamed?(name)

          fallback = reader_name(name)
          if names.include?(fallback) || Ident.reserved_column?(fallback)
            raise ArgumentError, "table #{table.name}: column #{name.inspect} can be neither #{name.inspect} nor " \
                                 "#{fallback.inspect} (a Ruby keyword or a Cybertrain::Model or Object method " \
                                 "owns the first, a column the second); rename a column"
          end
        end
        nil
      end

      def self.emit_relation(model)
        src = +""
        src << "class #{model}Relation < Cybertrain::Relation\n"
        src << "  def where(h) = (add_where(h); self)\n"
        src << "  def where_sql(s, b = []) = (add_where_sql(s, b); self)\n"
        src << "  def order(o) = (set_order(o); self)\n"
        src << "  def order_sql(s) = (add_order_sql(s); self)\n"
        src << "  def limit(n) = (set_limit(n); self)\n"
        src << "  def offset(n) = (set_offset(n); self)\n"
        src << "\n"
        src << "  def to_a\n"
        src << "    out = Array.new(0) { #{model}.new }\n"
        src << "    rows.each { |r| out << #{model}.from_row(r) }\n"
        src << "    out\n"
        src << "  end\n"
        src << "\n"
        src << "  def each(&blk) = to_a.each(&blk)\n"
        src << "\n"
        src << "  def first\n"
        src << "    r = first_row\n"
        src << "    return nil if r.nil?\n"
        src << "    #{model}.from_row(r)\n"
        src << "  end\n"
        src << "\n"
        src << "  def last\n"
        src << "    r = last_row\n"
        src << "    return nil if r.nil?\n"
        src << "    #{model}.from_row(r)\n"
        src << "  end\n"
        src << "\n"
        src << "  def find_by(h) = where(h).first\n"
        src << "\n"
        src << "  def find(id)\n"
        src << "    rec = where(id: id).first\n"
        src << "    raise Cybertrain::RecordNotFound, \"Couldn't find #{model} with id=\#{id}\" if rec.nil?\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src << "  def size = count\n"
        src << "end\n"
        src
      end

      def self.emit_model_head(model, table)
        src = +""
        names = table.columns.map { |c| c.name }
        quoted = names.map { |n| "\"#{n}\"" }.join(", ")
        symbols = names.map { |n| ":#{reader_name(n)}" }.join(", ")
        src << "class #{model} < Cybertrain::Model\n"
        src << "  def self.table_name = \"#{table.name}\"\n"
        src << "  def self.column_names = [\"id\", #{quoted}]\n"
        src << "  def model_name = \"#{model}\"\n"
        src << "\n"
        # attr_accessor, as before PR #10, on purpose. Typed `def x=(v)`
        # writers were tried there and had to go: under Spinel a `def x=` on
        # one class breaks the run-time dispatch of an `attr_accessor :x` on
        # another (NOTES rule 43) -- a column named body or status took
        # Response#body= / #status= down with it -- and column names are the
        # app's to choose. Probed on Spinel 2026.09.12: a Time assigned
        # through the raw writer to a nullable datetime ivar reads back
        # intact once load_row has typed the ivar via Cast.time_or_nil, so
        # rule 7 does not bite this shape.
        #
        # A column named like a method the framework calls on the record
        # (Ident::RESERVED_COLUMN_NAMES) or like a Ruby keyword reads as
        # `<column>_column` (reader, writer and ivar: reader_name); the
        # read_attribute / write_attribute keys below take either spelling
        # (attribute_keys).
        names.each do |n|
          src << "  " << rename_note(n) << "\n" if renamed?(n)
          next unless Ident.shadowing_column?(n)

          src << "  " << shadow_note("column", n) << "\n"
        end
        src << "  attr_accessor #{symbols}\n"
        src << "\n"
        src << "  def initialize(attrs = {})\n"
        src << "    super()\n"
        table.columns.each { |c| src << "    #{ivar_name(c.name)} = #{initial_value(c)}\n" }
        src << "    assign_attributes(attrs)\n"
        src << "  end\n"
        src << "\n"
        src << "  def self.from_row(row)\n"
        src << "    rec = #{model}.new\n"
        src << "    rec.load_row(row)\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src << "  def load_row(row)\n"
        src << "    set_id(Cybertrain::Cast.int(row[\"id\"]))\n"
        table.columns.each { |c| src << "    #{ivar_name(c.name)} = Cybertrain::Cast.#{cast_for(c)}(row[\"#{c.name}\"])\n" }
        src << "    mark_persisted!\n"
        src << "    nil\n"
        src << "  end\n"
        src << "\n"
        src << "  def read_attribute(name)\n"
        src << "    case name\n"
        src << "    when :id then @id\n"
        table.columns.each { |c| src << "    when #{attribute_keys(c.name)} then #{ivar_name(c.name)}\n" }
        src << "    else nil\n"
        src << "    end\n"
        src << "  end\n"
        src << "\n"
        src << "  def write_attribute(name, value)\n"
        src << "    case name\n"
        table.columns.each { |c| src << "    when #{attribute_keys(c.name)} then #{ivar_name(c.name)} = Cybertrain::Cast.#{cast_for(c)}(value)\n" }
        src << "    end\n"
        src << "    nil\n"
        src << "  end\n"
        src << "\n"
        src << "  def assign_attributes(attrs)\n"
        src << "    attrs.each { |k, v| write_attribute(k.to_s.to_sym, v) }\n"
        src << "    self\n"
        src << "  end\n"
        src << "\n"
        src << "  def to_row\n"
        src << "    {\n"
        pairs = table.columns.map { |c| "      \"#{c.name}\" => Cybertrain::Cast.to_sql(#{ivar_name(c.name)})" }.join(",\n")
        src << "#{pairs}\n"
        src << "    }\n"
        src << "  end\n"
        src << "\n"
        src
      end

      def self.emit_persistence(model, table)
        src = +""
        src << "  def self.all = #{model}Relation.new(\"#{table.name}\")\n"
        src << "  def self.where(h) = all.where(h)\n"
        src << "  def self.order(o) = all.order(o)\n"
        src << "  def self.order_sql(s) = all.order_sql(s)\n"
        src << "  def self.limit(n) = all.limit(n)\n"
        src << "  def self.find(id) = all.find(id)\n"
        src << "  def self.find_by(h) = all.find_by(h)\n"
        src << "  def self.first = all.first\n"
        src << "  def self.last = all.last\n"
        src << "  def self.count = all.count\n"
        src << "\n"
        src << "  def self.create(attrs = {})\n"
        src << "    rec = #{model}.new(attrs)\n"
        src << "    rec.save\n"
        src << "    rec\n"
        src << "  end\n"
        src << "\n"
        src
      end

      # Associations, then the read_association / call_view_method case
      # tables the template interpreter dispatches through by name.
      #
      # The name of an association reader. It is a method on the model like
      # any column reader, so it must be free: not a column, not another
      # association, not a Ruby keyword, not a method of Cybertrain::Model
      # or Object that the framework calls (`errors`, `attributes`, `raise`,
      # ... -- Ident). When the plain name is owned, the reader takes the
      # fallback instead of being dropped (as it was before PR #10) or
      # aborting the generator (which would break an existing schema on
      # upgrade): `<table>_as_<stem>` for a has_many, `<stem>_as_<column>`
      # for a belongs_to, and the generated file carries a note. Only both
      # names being owned is an error.
      def self.association_name(table, plain, fallback, kind, taken, assoc_names)
        return plain unless owned?(plain, taken, assoc_names)

        if owned?(fallback, taken, assoc_names)
          raise ArgumentError, "table #{table.name}: the #{kind} association can be neither #{plain.inspect} nor " \
                               "#{fallback.inspect} (a column, another association, a Cybertrain::Model method or a " \
                               "Ruby keyword owns each); rename a column"
        end
        fallback
      end

      def self.owned?(name, taken, assoc_names)
        taken.include?(name) || assoc_names.include?(name) || Ident.keyword?(name) || Ident.reserved_column?(name)
      end

      # A keyword is not a method of anything: say so instead of the
      # Model-method wording (the other cases keep their exact text).
      def self.association_note(kind, plain, name)
        if Ident.keyword?(plain)
          return "# #{kind} reads as #{name}: #{plain.inspect} is a Ruby keyword"
        end

        "# #{kind} reads as #{name}: #{plain.inspect} is a column, another association or a Cybertrain::Model method"
      end

      # Same note a column gets (emit_model_head) when the reader's name is an
      # Object method nothing in Cybertrain calls on a record: the association
      # keeps its name, the generated file says what it shadows.
      def self.shadow_note(what, name)
        "# NOTE: #{what} #{name.inspect} shadows Object##{name} on this model (nothing in " \
          "Cybertrain calls it on a record; Ident::SHADOWING_COLUMN_NAMES)"
      end

      # The note beside the attr_accessor of a column reader_name renamed.
      # Every note ends by telling that queries take the SQL name (the reader
      # name is not a column to Relation). A keyword is told so, not that it
      # is a method. The interpreter
      # resolves `errors` and `to_param` as model methods before it asks
      # read_attribute (Interpreter#model_method), so for those two the plain
      # name never reaches the column from a template and the note says so;
      # every other renamed name falls through to read_attribute and works
      # under either spelling.
      def self.rename_note(name)
        if Ident.keyword?(name)
          kw = "# column #{name.inspect} reads as #{reader_name(name)}: #{name.inspect} is a Ruby keyword"
          return kw + query_note(name)
        end

        note = "# column #{name.inspect} reads as #{reader_name(name)}: #{name.inspect} is a method of " \
          "Cybertrain::Model or Object that the framework calls (Ident::RESERVED_COLUMN_NAMES)"
        if name == "errors" || name == "to_param"
          note += "; templates resolve #{name} as that method, so a template reads the column as #{reader_name(name)}"
        end
        note + query_note(name)
      end

      # The clause every rename note ends with: where / order / find_by quote
      # the name as an SQL identifier, so only the SQL name is a column there.
      def self.query_note(name)
        "; queries (where, order, find_by) take the SQL name #{name.inspect}"
      end

      def self.emit_dispatch(table, definition, view_methods)
        src = +""
        # Both spellings of every column are owned: its SQL name and its
        # reader (they differ for a reserved name), so an association cannot
        # land on a renamed reader.
        taken = table.columns.map { |c| c.name }
        table.columns.each { |c| taken << reader_name(c.name) }
        taken << "id"
        assoc_names = Array.new(0) { "" }
        assoc_defs = Array.new(0) { "" }

        # belongs_to: comments.post_id -> def post (posts.author_id next to an
        # `author` column -> def author_as_author_id)
        table.foreign_keys.each do |fk|
          col = fk.column
          next unless col.end_with?("_id") && !table.column(col).nil?

          plain = col[0, col.size - 3]
          name = association_name(table, plain, plain + "_as_" + col, "belongs_to (from #{col})", taken, assoc_names)
          assoc_names << name
          assoc_defs << association_note("belongs_to " + col, plain, name) if name != plain
          assoc_defs << shadow_note("belongs_to reader", name) if Ident.shadowing_column?(name)
          assoc_defs << "def #{name} = #{model_class_name(fk.to_table)}.find_by(id: #{ivar_name(col)})"
        end

        # has_many: another table's foreign key pointing here -> def comments.
        # When that table points here through more than one column
        # (messages.sender_id and messages.recipient_id both -> users), each
        # gets its own name, `<table>_as_<column stem>` (def messages_as_sender,
        # def messages_as_recipient), so no key is dropped and the names do
        # not depend on declaration order; the same name is the fallback when
        # a column, a belongs_to reader or a Model method owns the plain one
        # (articles.comments TEXT next to comments.article_id -> def
        # comments_as_article).
        definition.tables.each do |other|
          next if other.name == table.name

          pointing = other.foreign_keys.select { |fk| fk.to_table == table.name }
          pointing.each do |fk|
            as_stem = other.name + "_as_" + column_stem(fk.column)
            # Two FKs: the plain name is already the `_as_<stem>` form, so the
            # fallback uses the whole column (messages_as_sender_id).
            plain = pointing.size > 1 ? as_stem : other.name
            fallback = pointing.size > 1 ? other.name + "_as_" + fk.column : as_stem
            name = association_name(table, plain, fallback, "has_many (#{other.name}.#{fk.column})", taken, assoc_names)
            assoc_names << name
            assoc_defs << association_note("has_many #{other.name}", plain, name) if name != plain
            assoc_defs << shadow_note("has_many reader", name) if Ident.shadowing_column?(name)
            assoc_defs << "def #{name} = #{model_class_name(other.name)}Relation.new(\"#{other.name}\")" \
                          ".where(#{fk.column}: @id).to_a"
          end
        end

        methods = Array.new(0) { "" }
        view_methods.each do |m|
          next if taken.include?(m) || assoc_names.include?(m) || methods.include?(m)

          methods << m
        end

        unless assoc_defs.empty?
          assoc_defs.each { |d| src << "  #{d}\n" }
          src << "\n"
        end
        src << emit_case("read_association", assoc_names)
        src << "\n" unless assoc_names.empty? && methods.empty?
        src << emit_case("call_view_method", methods)
        src
      end

      # "sender_id" -> "sender"; a column without the suffix is its own stem.
      def self.column_stem(column)
        column.end_with?("_id") ? column[0, column.size - 3] : column
      end

      # A `case name` over `names`; a one-line `nil` stub when there are
      # none, since a `case` without any `when` does not parse.
      def self.emit_case(method, names)
        src = +""
        if names.empty?
          src << "  def #{method}(name) = nil\n"
          return src
        end
        src << "  def #{method}(name)\n"
        src << "    case name\n"
        # `self.` because a reader may be capitalised (Ident.column? admits
        # `Author_id` -> def Author): bare, Ruby would read `Author` as a
        # constant.
        names.each { |n| src << "    when :#{n} then self.#{n}\n" }
        src << "    else nil\n"
        src << "    end\n"
        src << "  end\n"
        src
      end

      # The Cast helper that reads and writes this column (spikes/NOTES.md
      # rule 7: Time ivars always go through time_or_nil).
      def self.cast_for(column)
        null = column.null
        case column.type
        when :integer then null ? "int_or_nil" : "int"
        when :float then null ? "float_or_nil" : "float"
        when :boolean then null ? "bool_or_nil" : "bool"
        when :datetime then "time_or_nil"
        when :date then "str_or_nil"
        else null ? "str_or_nil" : "str"
        end
      end

      # The ivar's value in `initialize`: the column's SQL default when it
      # has a simple one (INSERT writes every column, so the database's own
      # DEFAULT never applies), else "" / 0 / 0.0 / false for NOT NULL
      # columns and nil for nullable ones. Nullable columns with a default
      # still go through their Cast helper to keep the ivar's nullable type.
      def self.initial_value(column)
        return "nil" if column.type == :datetime || column.type == :date

        literal = default_literal(column)
        if column.null
          literal == "" ? "nil" : "Cybertrain::Cast.#{cast_for(column)}(#{literal})"
        elsif literal != ""
          literal
        else
          case column.type
          when :integer then "0"
          when :float then "0.0"
          when :boolean then "false"
          else "\"\""
          end
        end
      end

      # The Ruby literal for a column's SQL default text ("0", "'x'",
      # "false"), or "" when there is none or it is not a plain literal.
      def self.default_literal(column)
        raw = column.default
        return "" if raw.nil?

        text = raw.strip
        return "" if text.upcase == "NULL"

        case column.type
        when :integer
          integer_text?(text) ? text : ""
        when :float
          if integer_text?(text)
            text + ".0"
          elsif float_text?(text)
            text
          else
            ""
          end
        when :boolean
          if text == "true" || text == "TRUE" || text == "1" || text == "'t'"
            "true"
          elsif text == "false" || text == "FALSE" || text == "0" || text == "'f'"
            "false"
          else
            ""
          end
        when :string, :text
          quoted_sql?(text) ? ruby_string(text[1, text.size - 2].gsub("''", "'")) : ""
        else
          ""
        end
      end

      def self.integer_text?(text)
        digits = text.start_with?("-") ? text[1, text.size - 1] : text
        return false if digits == ""

        digits.each_char { |ch| return false unless ch >= "0" && ch <= "9" }
        true
      end

      def self.float_text?(text)
        dot = text.index(".")
        return false if dot.nil?

        integer_text?(text[0, dot]) && integer_text?("0" + text[dot + 1, text.size - dot - 1])
      end

      def self.quoted_sql?(text)
        text.size >= 2 && text.start_with?("'") && text.end_with?("'")
      end

      # A double-quoted Ruby literal for `str`, with `#{` / `#$` / `#@`
      # escaped so the generated file never interpolates.
      def self.ruby_string(str)
        out = +"\""
        chars = str.chars
        chars.each_with_index do |ch, i|
          nxt = i + 1 < chars.size ? chars[i + 1] : ""
          if ch == "\\"
            out << "\\\\"
          elsif ch == "\""
            out << "\\\""
          elsif ch == "\n"
            out << "\\n"
          elsif ch == "#" && (nxt == "{" || nxt == "$" || nxt == "@")
            out << "\\#"
          else
            out << ch
          end
        end
        out << "\""
        out
      end
    end
  end
end
