require "cybertrain/generator/inflector"
require "cybertrain/generator/routes_dsl"

module Cybertrain
  module Gen
    # Writes gen/routes.rb: Gen::Routes.build (one router.add per route, each
    # calling its controller action by literal name), Gen::Routes.path_for
    # (helpers by String name, for templates) and Gen::UrlHelpers (one
    # *_path/*_url method per named route, mixed into every controller).
    module RoutesEmitter
      def self.emit(specs)
        named = specs.select { |s| s.helper_name != "" }
        out = +""
        out << "# Generated by `spin run gen` from config/routes.rb. Do not edit.\n"
        out << "require \"cybertrain/generator/url_support\"\n"
        out << "\n"
        out << "module Gen\n"
        out << "  module Routes\n"
        out << "    def self.build(router)\n"
        specs.each do |s|
          out << "      router.add(\"#{s.verb}\", #{quote(s.pattern)}, \"#{s.name}\") { |ctx| #{s.handler_source} }\n"
        end
        out << "      router\n"
        out << "    end\n"
        out << "\n"
        out << path_for_source(named)
        out << "  end\n"
        out << "\n"
        out << "  module UrlHelpers\n"
        named.each_with_index do |s, i|
          out << "\n" if i > 0
          out << helpers_source(s)
        end
        out << "  end\n"
        out << "end\n"
        out << "\n"
        out << "class Cybertrain::Controller\n"
        out << "  include ::Gen::UrlHelpers\n"
        out << "end\n"
        out
      end

      # Emitters build their own buffer and return it: under Spinel, appends
      # to a String received as an argument do not reach the caller's copy.
      def self.path_for_source(named)
        out = +""
        if named.empty?
          out << "    def self.path_for(name, args)\n"
          out << "      raise ArgumentError, \"unknown route helper '\#{name}'\"\n"
          out << "    end\n"
          return out
        end

        example = named.last
        out << "    # The helper named by a String, for templates: path_for(\"#{example.helper_name}_path\", [#{arg_names(example.pattern).join(", ")}]).\n"
        out << "    def self.path_for(name, args)\n"
        out << "      case name\n"
        named.each do |s|
          args = []
          arg_names(s.pattern).each_with_index { |_, i| args << "args[#{i}]" }
          path = path_expr(s.pattern, args)
          out << "      when \"#{s.helper_name}_path\" then #{path}\n"
          out << "      when \"#{s.helper_name}_url\" then Cybertrain.url_root + #{path}\n"
        end
        out << "      else raise ArgumentError, \"unknown route helper '\#{name}'\"\n"
        out << "      end\n"
        out << "    end\n"
        out
      end

      def self.helpers_source(spec)
        out = +""
        names = arg_names(spec.pattern)
        params = names.empty? ? "" : "(#{names.join(", ")})"
        out << "    def #{spec.helper_name}_path#{params}\n"
        out << "      #{path_expr(spec.pattern, names)}\n"
        out << "    end\n"
        out << "\n"
        out << "    def #{spec.helper_name}_url#{params}\n"
        out << "      Cybertrain.url_root + #{spec.helper_name}_path#{params}\n"
        out << "    end\n"
        out
      end

      # Helper parameter names for a pattern's dynamic segments:
      # ":post_id" -> "post", ":id" after "comments" -> "comment", ":slug" -> "slug".
      def self.arg_names(pattern)
        names = []
        previous = ""
        pattern.split("/").each do |seg|
          next if seg.empty?

          if seg.start_with?(":")
            key = seg[1, seg.size - 1]
            name = if key.end_with?("_id") && key.size > 3
                     key[0, key.size - 3]
                   elsif key == "id" && previous != ""
                     Inflector.singularize(previous)
                   else
                     key
                   end
            name = "#{name}#{names.size + 1}" if names.include?(name)
            names << name
          else
            previous = seg
          end
        end
        names
      end

      # A Ruby string literal for the pattern with each dynamic segment
      # replaced by Cybertrain::Gen.segment(<arg>).
      def self.path_expr(pattern, args)
        body = +""
        i = 0
        pattern.split("/").each do |seg|
          next if seg.empty?

          body << "/"
          if seg.start_with?(":")
            body << "\#{Cybertrain::Gen.segment(#{args[i]})}"
            i += 1
          else
            body << escape(seg)
          end
        end
        body = +"/" if body.empty?
        "\"#{body}\""
      end

      def self.quote(str)
        "\"#{escape(str)}\""
      end

      # Escapes a String for the inside of a double-quoted Ruby literal.
      def self.escape(str)
        out = +""
        str.each_char do |ch|
          out << "\\" if ch == "\\" || ch == "\"" || ch == "#"
          out << ch
        end
        out
      end
    end
  end
end
