module Cybertrain
  module Gen
    # Cybertrain::Gen::ViewsEmitter -- writes gen/views.rb, the table a
    # production binary renders views from (Template::Engine.embedded).
    #
    # Plain `spin run gen` writes an empty table: the committed state, so
    # editing a view never dirties gen/, and a development binary reads
    # app/views/ from disk. `spin run gen -- --embed-views` (what
    # `cybertrain build` runs before `spin build`, reverting afterwards)
    # writes every file under app/views/ as a string literal, and makes
    # production the default CYBERTRAIN_ENV of that binary.
    module ViewsEmitter
      HEADER = "# Generated by `spin run gen`. Do not edit.\n"

      def self.emit(root, embed)
        embed ? emit_embedded(root) : emit_empty
      end

      def self.emit_empty
        HEADER +
          "# Empty: this build reads app/views/ from disk. `spin run gen -- --embed-views`\n" \
          "# (what `cybertrain build` runs) fills it and the binary stops reading disk.\n" +
          empty_sources_module
      end

      def self.emit_embedded(root)
        dir = "#{root}/app/views"
        files = view_files(dir)
        buf = +HEADER
        if files.size == 0
          # No views to embed: still a typed empty Hash (seed-then-delete),
          # never a bare `{}` -- an untyped empty Hash literal risks a
          # Spinel compile failure (spikes/NOTES.md rule 9).
          buf << empty_sources_module
        else
          buf << "module Gen\n  module Views\n    SOURCES = {\n"
          files.each do |rel|
            buf << "      #{literal(rel)} => #{literal(File.read("#{dir}/#{rel}"))},\n"
          end
          buf << "    }\n  end\nend\n"
        end
        buf << "ENV[\"CYBERTRAIN_ENV\"] = \"production\" if (ENV[\"CYBERTRAIN_ENV\"] || \"\").empty?\n"
        buf
      end

      # The typed-empty `Gen::Views::SOURCES` table (seed-then-delete, per
      # spikes/NOTES.md rule 9), shared by the plain-empty build and an
      # embedded build with nothing under app/views.
      def self.empty_sources_module
        "module Gen\n" \
          "  module Views\n" \
          "    SOURCES = { \"\" => \"\" }\n" \
          "    SOURCES.delete(\"\")\n" \
          "  end\n" \
          "end\n"
      end

      # A double-quoted literal Spinel and CRuby read back to the same
      # bytes: only the six characters that need escaping are escaped;
      # UTF-8 passes through raw (verified by spike, 2026-09-26).
      def self.literal(text)
        escaped = text.gsub("\\", "\\\\\\\\").gsub("\"", "\\\"").gsub("#", "\\#")
                      .gsub("\n", "\\n").gsub("\r", "\\r").gsub("\t", "\\t")
        "\"#{escaped}\""
      end

      # Every regular file under dir, as sorted paths relative to dir.
      def self.view_files(dir)
        files = Array.new(0) { "" }
        collect(dir, "", files)
        files.sort
      end

      def self.collect(dir, prefix, files)
        return nil unless File.directory?(dir)

        Dir.children(dir).sort.each do |entry|
          path = "#{dir}/#{entry}"
          rel = prefix == "" ? entry : "#{prefix}/#{entry}"
          if File.directory?(path)
            collect(path, rel, files)
          else
            files << rel
          end
        end
        nil
      end
    end
  end
end
