module Cybertrain
  module Gen
    # Cybertrain::Gen::ViewsEmitter -- writes gen/views.rb, the table a
    # production binary renders views from (Template::Engine.embedded).
    #
    # Plain `spin run gen` writes an empty table: the committed state, so
    # editing a view never dirties gen/, and a development binary reads
    # app/views/ from disk. `spin run gen -- --embed-views` (what
    # `cybertrain build` runs before `spin build`, reverting afterwards)
    # writes every *.erb under app/views/ as a string literal (dotfiles,
    # other files and symlinked directories are skipped), and makes
    # production the default CYBERTRAIN_ENV of that binary.
    module ViewsEmitter
      HEADER = "# Generated by `spin run gen`. Do not edit.\n"

      def self.emit(root, embed)
        embed ? emit_embedded(root) : emit_empty
      end

      def self.emit_empty
        HEADER +
          "# Empty: this build reads app/views/ from disk. `spin run gen -- --embed-views`\n" \
          "# (what `cybertrain build` runs) fills it and the binary stops reading disk.\n" +
          empty_sources_module
      end

      def self.emit_embedded(root)
        dir = "#{root}/app/views"
        files = view_files(dir)
        buf = +HEADER
        if files.size == 0
          # No views to embed: still a typed empty Hash (seed-then-delete),
          # never a bare `{}` -- an untyped empty Hash literal risks a
          # Spinel compile failure (spikes/NOTES.md rule 9).
          buf << empty_sources_module
        else
          buf << "module Gen\n  module Views\n    SOURCES = {\n"
          files.each do |rel|
            buf << "      #{literal(rel)} => #{literal(File.read("#{dir}/#{rel}"))},\n"
          end
          buf << "    }\n  end\nend\n"
        end
        buf << "ENV[\"CYBERTRAIN_ENV\"] = \"production\" if (ENV[\"CYBERTRAIN_ENV\"] || \"\").empty?\n"
        buf
      end

      # The typed-empty `Gen::Views::SOURCES` table (seed-then-delete, per
      # spikes/NOTES.md rule 9), shared by the plain-empty build and an
      # embedded build with nothing under app/views.
      def self.empty_sources_module
        "module Gen\n" \
          "  module Views\n" \
          "    SOURCES = { \"\" => \"\" }\n" \
          "    SOURCES.delete(\"\")\n" \
          "  end\n" \
          "end\n"
      end

      HEX = "0123456789ABCDEF"

      # A double-quoted literal Spinel and CRuby read back to the same
      # bytes: backslash, `"` and `#` are escaped, newline, return and tab
      # become \n \r \t, every other control byte (< 0x20, 0x7f) becomes
      # \u00XX (NUL is \u0000); UTF-8 passes through raw (both verified by
      # spike, 2026-09-26).
      def self.literal(text)
        buf = +"\""
        text.each_char do |c|
          if c == "\\" then buf << "\\\\"
          elsif c == "\"" then buf << "\\\""
          elsif c == "#" then buf << "\\#"
          elsif c == "\n" then buf << "\\n"
          elsif c == "\r" then buf << "\\r"
          elsif c == "\t" then buf << "\\t"
          elsif c.bytesize == 1 && (c.bytes[0] < 0x20 || c.bytes[0] == 0x7f)
            b = c.bytes[0]
            buf << "\\u00" << HEX[b / 16] << HEX[b % 16]
          else
            buf << c
          end
        end
        buf << "\""
        buf
      end

      # Every template (*.erb) under dir, as sorted paths relative to dir.
      # Dotfiles (.DS_Store, editor swap files) and other files are left
      # out: the engine only looks up .erb keys. A symlinked directory is
      # not descended into (no cycles).
      def self.view_files(dir)
        files = Array.new(0) { "" }
        collect(dir, "", files)
        files.sort
      end

      def self.collect(dir, prefix, files)
        return nil unless File.directory?(dir)

        Dir.children(dir).sort.each do |entry|
          path = "#{dir}/#{entry}"
          rel = prefix == "" ? entry : "#{prefix}/#{entry}"
          next if entry.start_with?(".")

          if File.directory?(path)
            collect(path, rel, files) unless File.symlink?(path)
          elsif entry.end_with?(".erb")
            files << rel
          end
        end
        nil
      end
    end
  end
end
